### PR TITLE
Board category parse desc

### LINKED ISSUE #5734: getBoardindex do call parse_bbc which takes 94% of the run time
#### Description
notice in my test board,
that the generation goes up from ~ 0.060 ms to ~0.340 ms.
By cecking the trace i notice that the parse_bbc and calls below create 94% of the call time:

grafik

trace file: https://mega.nz/#!W8piDSKa!6qkqASjhWj80unkS8uAY_XvFW5iwHYRhJZtdjjScyik

issue is introduce by pr: #5704 from @MissAllSunday 
because of this line: 
https://github.com/SimpleMachines/SMF2.1/blob/e941ff2b0b31fe44a8aeb9ca435ff6231d5eaa26/Sources/Subs-BoardIndex.php#L263
### Steps to reproduce
1.  time notice on the start page

### Environment (complete as necessary)
- Version/Git revision: e941ff2b0
- Database Type:
- Database Version:
- PHP Version: 7.2

### Additional information/references

### PR DESCRIPTION
**Pull request by MissAllSunday**
Fixes #5734

Made a refactor on how to parse and save the parsed content on the cache.

Its a somehow atomic approach, the get and set operations are done on a per category and per board basis, this means an user who can only see a subset of the total boards won't get the load of parsing all of them.

Tested with filebased and SQLite3

### CODE REVIEW

**Comment by MissAllSunday** [comment]
Ugh, I forgot to replace the data with its parsed counterpart. Its late so I'll do it later.

**Comment by albertlast** [comment]
> Some poor soul will get the hit of parsing the entire categories and boards names and descriptions but there isn't much we can do about it.

How would be to allow to disable this feature like "recent post function"?

And how long run you change on ~100 board forum in compare to the existing one?

**Comment by MissAllSunday** [comment]
I don't understand what you mean by disable this feature. No it cannot be disable unless you don't use cache at all.

You won't be able to measure this against other alternatives. This approach adds to the cache as needed.  The query uses {query_see_board} which means the load of parsing the names and description will be shared among several users since all of them will have access to different boards.

Every time there's something new to parse, the cache gets refreshed and the new data gets appended to what we already have. The cache also has a long time duration since boards and categories aren't updated that frequently.

Lastly, having the cache by category means we will end up with fewer cache entries of a moderate size.

I also need to re-create the cache whenever a board is created/updated. Will add that too.

**Comment by albertlast** [comment]
I don't see the bcode parsing feature in general as essential,
so i would purpose to allow to disable the parsing function to safe runtime/cpu time.

I do all the time measurements, first alternative is the version before you add you first pr,
the secodn one is the merge version right now.

for both cases: with cache and none cache.

**Comment by MissAllSunday** [comment]
> I do all the time measurements, first alternative is the version before you add you first pr,
the secodn one is the merge version right now.

Cool. What I'm saying is that if you try to measure this using an admin account who can see 100 boards then you won't be able to see much improvements.

**Comment by albertlast** [comment]
sm.org would already reach the point and
i'm waiting for measurments...

**Comment by MissAllSunday** [comment]
> sm.org would already reach the point and

???

File: Sources/Subs-BoardIndex.php [hunk 1]
```diff
@@ -95,7 +95,7 @@ function getBoardIndex($boardIndexOptions)
 	else
 		$result_boards = $smcFunc['db_query']('', '
 			SELECT' . ($boardIndexOptions['include_categories'] ? '
-				c.id_cat, c.name AS cat_name, c.description AS cat_desc,' : '') . '
+				c.id_cat, c.name AS cat_name, c.description AS cat_desc,' : 'b.id_cat,') . '
```
Comment (albertlast) [inline Sources/Subs-BoardIndex.php]: i would also then change the c.id_cat to b.id_cat in the first position

**Review by albertlast — COMMENTED** [review]
only look throw the code

**Comment by albertlast** [comment]
While testing i get two kind of errors:
```
Error

    Type of error: Undefined_vars
    Error message: 8: Undefined index: description
    File: F:/github/SMF2.1/Sources/Subs-BoardIndex.php
    Line: 621
    URL of page causing the error: http://localhost/SMF2.1/index.php?

Backtrace information

    #0: smf_error_handler()
    Called from F:\github\SMF2.1\Sources\Subs-BoardIndex.php on line 621
    #1: setParsedDescriptions()
    Called from F:\github\SMF2.1\Sources\Subs-BoardIndex.php on line 548
    #2: getBoardIndex()
    Called from F:\github\SMF2.1\Sources\BoardIndex.php on line 49
    #3: BoardIndex()
    Called from F:\github\SMF2.1\index.php on line 155

```

and
```
Error

    Type of error: Undefined_vars
    Error message: 8: Undefined index: name
    File: F:/github/SMF2.1/Sources/Subs-BoardIndex.php
    Line: 620
    URL of page causing the error: http://localhost/SMF2.1/index.php?

Backtrace information

    #0: smf_error_handler()
    Called from F:\github\SMF2.1\Sources\Subs-BoardIndex.php on line 620
    #1: setParsedDescriptions()
    Called from F:\github\SMF2.1\Sources\Subs-BoardIndex.php on line 548
    #2: getBoardIndex()
    Called from F:\github\SMF2.1\Sources\BoardIndex.php on line 49
    #3: BoardIndex()
    Called from F:\github\SMF2.1\index.php on line 155
```

with this i can't test you changes,
only when i disable cache(used APCu) i can run your code fine,
ther i notice that your code run slower as the existing solution.

File: Sources/Subs-BoardIndex.php [hunk 2]
```diff
@@ -470,13 +544,141 @@ function getBoardIndex($boardIndexOptions)
 		$context['latest_post'] = $latest_post['ref'];
 	}
 
+	// I took my time, I hurried up, the choice was mine I didn't think enough
+	$parsed_descriptions = setparsedDescriptions($to_parse);
```
Comment (live627) [inline Sources/Subs-BoardIndex.php]: Just a tiny nitpick here... sorry... case doesn't match

Comment (MissAllSunday) [reply Sources/Subs-BoardIndex.php]: case?

Comment (albertlast) [reply Sources/Subs-BoardIndex.php]: i guess it should be setParsedDescriptions

**Comment by MissAllSunday** [comment]
Made a refactor on how to parse and save the parsed content on the cache.

Its a somehow atomic approach, the get and set operations are done on a per category and per board basis, this means an user who can only see a subset of the total boards won't get the load of parsing all of them.

Tested with filebased and SQLite3.

Please give it a test.

**Comment by albertlast** [comment]
When you switch from caching back to non caching,
stuff get lost:
grafik

Since this bug i can't fully do a performance test,
but partial:
You new version is 10ms faster as the existing code in a cached env.
Non cached env is missing of this bug mention of the start

**Comment by MissAllSunday** [comment]
Added yet another refactor, grouping both categories and board caches, now there's a single cache entry for all categories and board cache is grouped by category, reducing the amount of hits to get the cached data.

**Comment by MissAllSunday** [comment]
I removed support for parsing the board/cat name its just too much hassle to make sure the parsed result won't mess up all the different places where the board name is displayed.

Also due to the call to clean_cache when a board is been created/modified all cache data will be lost, I added support for keeping the cache data for all the other boards on the same category but the rest will get cleaned.
