### PR TITLE
Add some fixes for Memcache/Memcached caching variants

### LINKED ISSUE #6432: Missing help string for Memcached servers
#### Description
$helptxt['cache_memcachedimplementation'] does not exist (Help.english.php)
2020-12-28 00_59_58-Server Settings — Firefox Developer Edition

### Steps to reproduce
1. Go to Maintenance -> Server settings -> Caching
2. Press the help button for Memcached servers

### Environment (complete as necessary)
- Version/Git revision: 4ba5dd2

### PR DESCRIPTION
**Pull request by dragomano**
This PR is a more simple alternative to #6444
Also, it fixes #6432 

2021-01-16 18_15_24-Server Settings — Firefox Developer Edition

Close #6444

Signed-off-by: Bugo <bugo@dragomano.ru>

### CODE REVIEW

File: Sources/Cache/APIs/MemcachedImplementation.php [hunk 1]
```diff
@@ -49,7 +49,10 @@ function($server)
 					return array($server, 0);
 
 				else
-					return array($server, isset($server[1]) ? (int) $server[1] : 11211);
+				{
+					$server = explode(':', $server);
+					return array($server[0], isset($server[1]) ? (int) $server[1] : 11211);
```
Comment (albertlast) [inline Sources/Cache/APIs/MemcachedImplementation.php:54]: didn't looked at the other pr,
but we expect that the memcached is connect by ipv4 right?

Comment (dragomano) [reply Sources/Cache/APIs/MemcachedImplementation.php:54]: Right
