### PR TITLE
Hide Quote selected text button on deselect text

### LINKED ISSUE #6716: Bugged mouse selection does not reset on click
#### Description
Usually if you select anything in the internet with your mouse pointer, you can click inside selected area and this resets the selection. But not inside SMF 2.1 posts ... Why? Selection can only be reset by clicking outside selected area.
Selection here is not html select but, clipboard select.

### Steps to reproduce
1. open any smf post
2. keydown left mouse button and move it to select some text
3. click inside selected text to reset selection
4. no you can't ...

### Environment (complete as necessary)
- Version/Git revision: RC3

### PR DESCRIPTION
**Pull request by BrickOzp**
If clicking outside the post div to deselect text, did not
hide the "Quote selected text" button. Fixed that by
adding a global click listener.

Fixes #6716

Signed-off-by: Oscar Rydhé <oscar.rydhe@gmail.com>

### CODE REVIEW

File: Themes/default/scripts/quotedText.js [hunk 1]
```diff
@@ -119,27 +119,41 @@ $(function() {
...
+		// Register global on click listener to catch deselect clicks outside of the div.
+		$(document).on('click.ondeselecttext' + oSelected.msgID, function() {
+			// Delay the check a bit to allow the deselection to happen.
+			setTimeout(function() {
+				selectedText = getSelectedText(oSelected.divID);
+
+				if (typeof selectedText != 'undefined' && selectedText != false)
+					return;
+
+				// Revome any 'click' event to the button.
```
Comment (live627) [inline Themes/default/scripts/quotedText.js]:
```suggestion
				// Remove any 'click' event to the button.
```

**Review by MissAllSunday — APPROVED** [review]
