### PR TITLE
Set default board profile when profile set to inherit

### LINKED ISSUE #6798: Out of range value for column 'id_profile' at row 1
#### Description
SQL database error at new board creation with non-standard access settings (not sure which one):
```sql
UPDATE smf_boards
			SET
				id_cat = 13,
				id_parent = 0,
				child_level = 0,
				board_order = 59,
				count_posts = 1,
				id_theme = 0,
				override_theme = 0,
				member_groups = '2,9',
				deny_member_groups = '',
				name = 'zzzzzzzzzzzzzzz',
				description = 'zzzzzzzzzzzzzzzzzzzzzzz',
				id_profile = -1,
				redirect = ''
			WHERE id_board = 129
```

### Steps to reproduce
Choose profile = -1 (first option) on board settings.

### Environment (complete as necessary)
- Version/Git revision: RC3
- Database Type: Mysql

### PR DESCRIPTION
**Pull request by BrickOzp**
If creating a new board with the profile set as
"Inherit from parent board" an error will occur.
The board will be created, but without most of the
set options. Fixed this by setting the default profile
if inherit is selected. After the board is created
a check is done to find the parent board profile
setting and copy it.

Fixes #6798

Signed-off-by: Oscar Rydhé <oscar.rydhe@gmail.com>

### CODE REVIEW

File: Sources/ManageBoards.php [hunk 1]
```diff
@@ -697,7 +697,7 @@ function EditBoard2()
 		$boardOptions['redirect'] = !empty($_POST['redirect_enable']) && isset($_POST['redirect_address']) && trim($_POST['redirect_address']) != '' ? trim($_POST['redirect_address']) : '';
 
 		// Profiles...
-		$boardOptions['profile'] = $_POST['profile'];
+		$boardOptions['profile'] = $_POST['profile'] == -1 ? 1 : $_POST['profile'];
```
Comment (frandominguezl) [inline Sources/ManageBoards.php:700]: I have a question. Is there a reason why you chose `==` instead of `===`?

Comment (BrickOzp) [reply Sources/ManageBoards.php:700]: It was like that on the row below

Comment (frandominguezl) [reply Sources/ManageBoards.php:700]: Enough for me, thanks!

**Review by Sesquipedalian — APPROVED** [review]

**Comment by Oldiesmann** [comment]
Does this account for the profile of the parent board changing at some point?

**Comment by BrickOzp** [comment]
This PR does not change the behavior of this. SMF will copy the parent profile id at creation time, it will not be changed later if the parent changes. Subs-Boards.php line 944
