### PR TITLE
Only remove not uploaded attachments on cancel all

### LINKED ISSUE #6388: Cancel all button removes uploaded attachments
#### Description
Using the cancel all button when an attachment already is uploaded will remove also that attachment from the list.
But when posting the message, that attachment is attached.
By using this way you can upload more attachments than the maximum allowed.

The upload all and cancel all buttons are not hidden when not needed.

### Steps to reproduce
1. Attach a file and upload it.
2. Attach another file without uploading it.
3. Press cancel all.
4. Both attachments are removed.
5. Post the message.
6. The first attachment is attached.

### Environment (complete as necessary)
- Version/Git revision: d43b0f
- Database Type: mysql
- Database Version:
- PHP Version: 5.6

### Additional information/references

### PR DESCRIPTION
**Pull request by BrickOzp**
The cancel all button should only cancel not already
uploaded attachments.
Also hide the cancel all and upload all buttons when
there are no files to cancel or upload.
Hide the progress bar when there are no attachments
at all.

Fixes #6388

Signed-off-by: Oscar Rydhé oscar.rydhe@gmail.com

### CODE REVIEW

File: Themes/default/scripts/smf_fileUpload.js [hunk 1]
```diff
@@ -515,4 +516,15 @@ function smf_fileUpload(oOptions) {
 			myDropzone.emit("complete", mock);
 		});
 	}
+
+	function hide_file_progress_and_all_buttons_if_needed() {
```
Comment (MissAllSunday) [inline Themes/default/scripts/smf_fileUpload.js]: nitpick: can you change the function name to camelCase please?

Maybe even change it to a closure and use it as a property of the parent function

Comment (BrickOzp) [reply Themes/default/scripts/smf_fileUpload.js]: Done

**Review by MissAllSunday — APPROVED** [review]
