### PR TITLE
Fix `TypeError` in RepairBoards

### LINKED ISSUE #8168: `TypeError` in Repair Boards
1. Populate forum  using `Populate.php`
2. Run to find errors 
3. Click `Yes` to fix all
4. Die in irony

```
<b>Fatal error</b>:  Uncaught TypeError: SMF\Actions\Admin\RepairBoards::fixMissingCachedSubject(): Argument #1 ($result) must be of type array, mysqli_result given in C:\wamp64\www\smf-dev\Sources\Actions\Admin\RepairBoards.php:2090
Stack trace:
#0 [internal function]: SMF\Actions\Admin\RepairBoards-&gt;fixMissingCachedSubject(Object(mysqli_result))
#1 C:\wamp64\www\smf-dev\Sources\Actions\Admin\RepairBoards.php(1086): call_user_func(Array, Object(mysqli_result))
#2 C:\wamp64\www\smf-dev\Sources\Actions\Admin\RepairBoards.php(832): SMF\Actions\Admin\RepairBoards-&gt;findForumErrors(true)
#3 C:\wamp64\www\smf-dev\Sources\Actions\Admin\RepairBoards.php(882): SMF\Actions\Admin\RepairBoards-&gt;execute()
#4 [internal function]: SMF\Actions\Admin\RepairBoards::call()
#5 C:\wamp64\www\smf-dev\Sources\Actions\Admin\ACP.php(786): call_user_func(Array)
#6 C:\wamp64\www\smf-dev\Sources\Actions\Admin\ACP.php(813): SMF\Actions\Admin\ACP-&gt;execute()
#7 [internal function]: SMF\Actions\Admin\ACP::call()
#8 C:\wamp64\www\smf-dev\Sources\Forum.php(263): call_user_func(Array)
#9 C:\wamp64\www\smf-dev\index.php(148): SMF\Forum-&gt;execute()
#10 {main}
  thrown in <b>C:\wamp64\www\smf-dev\Sources\Actions\Admin\RepairBoards.php</b> on line <b>2090</b><br />

### PR DESCRIPTION
**Pull request by live627**
Looks like this type is only passed to `fix_full_processing`,  and this is the only function that  uses it

### CODE REVIEW

File: Sources/Actions/Admin/RepairBoards.php [hunk 1]
```diff
@@ -2087,7 +2087,7 @@ protected function fixMissingNotifyMembers(array $members): void
 	 *
 	 * @param array $result Search result id
```
Comment (Sesquipedalian) [inline Sources/Actions/Admin/RepairBoards.php]: Should change here too

**Review by Sesquipedalian — CHANGES_REQUESTED** [review]

**Review by Sesquipedalian — APPROVED** [review]
