### PR TITLE
Fixing more open_basedir violations

### LINKED ISSUE #7744: [2.1.x] Open_basedir warnings with file permission profile
_Originally posted by @isaak654 in https://github.com/SimpleMachines/SMF/pull/7741#pullrequestreview-1414652291_

> When you set the file permission function `Use predefined permission profile: Standard`, it will produce multiple open_basedir warnings
> ```
>  Time of Error 	Today at 01:53 PM
> » Member ID that caused error 	1
> » URL that caused error 	https://AVforum2.altervista.org/index.php?action=admin;area=packages;sa=perms;e664666a=e29b63c81067f8ab59e118a8605c33f0
> » Error Message 	2: is_writable(): open_basedir restriction in effect. File(/membri/AVforum2/..) is not within the allowed path(s): (/membri/AVforum2/:/membri2/AVforum2/:/membri/.dummy/)
> File: /membri/AVforum2/Sources/Subs.php
> Line: 7222
> » Error Type 	general
> » Time of Error 	Today at 01:53 PM
> » Member ID that caused error 	1
> » URL that caused error 	https://AVforum2.altervista.org/index.php?action=admin;area=packages;sa=perms;e664666a=e29b63c81067f8ab59e118a8605c33f0
> » Error Message 	2: is_dir(): open_basedir restriction in effect. File(/membri/AVforum2/..) is not within the allowed path(s): (/membri/AVforum2/:/membri2/AVforum2/:/membri/.dummy/)
> File: /membri/AVforum2/Sources/Subs.php
> Line: 7213
> » Error Type 	general
> » Time of Error 	Today at 01:53 PM
> » Member ID that caused error 	1
> » URL that caused error 	https://AVforum2.altervista.org/index.php?action=admin;area=packages;sa=perms;e664666a=e29b63c81067f8ab59e118a8605c33f0
> » Error Message 	2: is_writable(): open_basedir restriction in effect. File(/membri/AVforum2/..) is not within the allowed path(s): (/membri/AVforum2/:/membri2/AVforum2/:/membri/.dummy/)
> File: /membri/AVforum2/Sources/Subs.php
> Line: 7209
> » Error Type 	general
> » Time of Error 	Today at 01:53 PM
> » Member ID that caused error 	1
> » URL that caused error 	https://AVforum2.altervista.org/index.php?action=admin;area=packages;sa=perms;e664666a=e29b63c81067f8ab59e118a8605c33f0
> » Error Message 	2: file_exists(): open_basedir restriction in effect. File(/membri/AVforum2/..) is not within the allowed path(s): (/membri/AVforum2/:/membri2/AVforum2/:/membri/.dummy/)
> File: /membri/AVforum2/Sources/Subs-Package.php
> Line: 2787
> » Error Type 	general
> » Time of Error 	Today at 01:53 PM
> » Member ID that caused error 	1
> » URL that caused error 	https://AVforum2.altervista.org/index.php?action=admin;area=packages;sa=perms;e664666a=e29b63c81067f8ab59e118a8605c33f0
> » Error Message 	2: file_exists(): open_basedir restriction in effect. File(/membri/AVforum2/..) is not within the allowed path(s): (/membri/AVforum2/:/membri2/AVforum2/:/membri/.dummy/)
> File: /membri/AVforum2/Sources/Subs-Package.php
> Line: 2775
> » Error Type 	general
> » Time of Error 	Today at 01:53 PM
> » Member ID that caused error 	1
> » URL that caused error 	https://AVforum2.altervista.org/index.php?action=admin;area=packages;sa=perms;e664666a=e29b63c81067f8ab59e118a8605c33f0
> » Error Message 	2: file_exists(): open_basedir restriction in effect. File(/membri/AVforum2/..) is not within the allowed path(s): (/membri/AVforum2/:/membri2/AVforum2/:/membri/.dummy/)
> File: /membri/AVforum2/Sources/Subs-Package.php
> Line: 2760
> » Error Type 	general
> » Time of Error 	Today at 01:53 PM
> » Member ID that caused error 	1
> » URL that caused error 	https://AVforum2.altervista.org/index.php?action=admin;area=packages;sa=perms;e664666a=e29b63c81067f8ab59e118a8605c33f0
> » Error Message 	2: is_dir(): open_basedir restriction in effect. File(/membri/AVforum2/..) is not within the allowed path(s): (/membri/AVforum2/:/membri2/AVforum2/:/membri/.dummy/)
> File: /membri/AVforum2/Sources/Packages.php
> Line: 2648
> » Error Type 	general
> ```

### Environment (complete as necessary)
- Version/Git revision: SMF 2.1.3
- Database: MySQL 8.0.26 
- PHP Version: 8.0.26 / 8.2.3

### Additional information/references
- open_basedir: `/membri/AVforum2/:/membri2/AVforum2/:/membri/.dummy/`
- php.ini can't be changed, even upon official request to the provider
- no apache log

### PR DESCRIPTION
**Pull request by live627**
Fix  #7744

@isaak654

### CODE REVIEW

File: Sources/Packages.php [hunk 1]
```diff
@@ -2644,6 +2644,9 @@ function build_special_files__recursive($path, &$data)
 			$dont_chmod = false;
 			while ($entry = readdir($dh))
 			{
+				if ($entry == '.' || $entry == '..')
+					continue;
```
Comment (isaak654) [inline Sources/Packages.php:2649]:
```suggestion
				// Bypass directory abbreviations altogether...
				if ($entry == '.' || $entry == '..')
					continue;
```

It works, but you forgot to comment it.

**Review by isaak654 — CHANGES_REQUESTED** [review]

File: Sources/Packages.php (hunk 1 above)
Comment (live627) [reply Sources/Packages.php:2649]: rather than argue with you, I'm just going to commit it

Comment (isaak654) [reply Sources/Packages.php:2649]: I wish you good luck and all the best.
