### PR TITLE
[2.1] Don't trust totalMembers

### LINKED ISSUE #8841: [3.0|2.1]: Admin member list omits inactive members
### Basic Information

https://www.simplemachines.org/community/index.php?topic=592451.0

### Steps to reproduce
According to the topic:
1. Log in as an admin user in a forum migrated from version 2.0.19 to 2.1.6.
2. Navigate to Admin > Members > View all Members.
3. Observe that inactive members are missing.

### Expected result

The admin member list is supposed to display every account on the forum regardless of activation status.

### Version/Git revision

2.1.6

### PR DESCRIPTION
**Pull request by jdarwood007**
Fixes #8841

### CODE REVIEW

File: Sources/Subs-Members.php [hunk 1]
```diff
@@ -1480,23 +1480,15 @@ function list_getNumMembers($where, $where_params = array())
...
-		);
-		list ($num_members) = $smcFunc['db_fetch_row']($request);
-		$smcFunc['db_free_result']($request);
-	}
+	$request = $smcFunc['db_query']('', '
+		SELECT COUNT(*)
+		FROM {db_prefix}members AS mem
+		WHERE ' . $where,
+		array_merge($where_params, array(
+		))
```
Comment (Sesquipedalian) [inline Sources/Subs-Members.php]:
```suggestion
		$where_params
```

**Review by Sesquipedalian — CHANGES_REQUESTED** [review]

**Review by Sesquipedalian — APPROVED** [review]
