### PR TITLE
Attach BBC

### LINKED ISSUE #5198: Message preview doesn't load with embedded attachments
#### Description
For some reason, if you try to load a preview in the post authoring page of a message that contains an embedded attachment using the [attach] BBC, the preview never loads. It just says "Fetching preview..." and never moves on.

### Steps to reproduce
1. Create or edit a post with an embedded attachment.
2. Click the Preview button.

### Environment (complete as necessary)
- Version/Git revision: 5a9c605
- Database Type: MySQL
- Database Version: 5.7.23
- PHP Version: 7.1.19

### Additional information/references

### PR DESCRIPTION
**Pull request by live627**
Fixes  #5198

### CODE REVIEW

File: Sources/Subs-Attachments.php [hunk 1]
```diff
@@ -1108,33 +1096,32 @@ function getAttachMsgInfo($attachID)
...
-				a.id_attach, a.id_folder, a.id_msg, a.filename, a.file_hash, COALESCE(a.size, 0) AS filesize, a.downloads, a.approved, m.id_topic AS topic, m.id_board AS board,
+				a.id_attach, a.id_folder, a.id_msg, a.filename, a.file_hash, COALESCE(a.size, 0) AS filesize, a.downloads, a.approved, m.id_topic AS topic, m.id_board AS board, m.id_member,
 				a.width, a.height' . (empty($modSettings['attachmentShowImages']) || empty($modSettings['attachmentThumbnails']) ? '' : ',
 				COALESCE(thumb.id_attach, 0) AS id_thumb, thumb.width AS thumb_width, thumb.height AS thumb_height') . '
 			FROM {db_prefix}attachments AS a' . (empty($modSettings['attachmentShowImages']) || empty($modSettings['attachmentThumbnails']) ? '' : '
 				LEFT JOIN {db_prefix}attachments AS thumb ON (thumb.id_attach = a.id_thumb)') . '
 				LEFT JOIN {db_prefix}messages AS m ON (m.id_msg = a.id_msg)
 			WHERE a.attachment_type = {int:attachment_type}
-				' . (!empty($msgID) ? 'AND a.id_msg = {int:message_id}' : '') . '',
+				AND a.id_msg ' . (!empty($context['preview_message']) ? 'IN (0, {int:message_id})' : 'AND a.id_msg = {int:message_id}') . '',
```
Comment (Sesquipedalian) [inline Sources/Subs-Attachments.php]:
```
AND a.id_msg ' . (!empty($context['preview_message']) ? 'IN (0, {int:message_id})' : '= {int:message_id}'),
```

File: Sources/Subs-Attachments.php [hunk 2]
```diff
@@ -1320,7 +1307,13 @@ function loadAttachmentContext($id_msg, $attachments)
 
 	// Do we need to instigate a sort?
 	if ($have_unapproved)
-		usort($attachmentData, 'approved_attach_sort');
+		uksort($attachmentData, function($a, $b)
```
Comment (Sesquipedalian) [inline Sources/Subs-Attachments.php]: Why did this change from a `usort()` to a `uksort()`?

**Review by Sesquipedalian — CHANGES_REQUESTED** [review]

File: Sources/Subs-Attachments.php (hunk 2 above)
Comment (live627) [reply Sources/Subs-Attachments.php]: the keys are required to remain unchanged for https://github.com/SimpleMachines/SMF2.1/pull/5574/files#diff-7773b8079c8a8f4db3a661335b297c20R983  otherwise you get undefined indexes while using the attach bbcode on unapproved attachments.

Comment (SychO9) [reply Sources/Subs-Attachments.php]: does that mean this PR should fix #5134 ?

Comment (live627) [reply Sources/Subs-Attachments.php]: No idea.

Comment (Sesquipedalian) [reply Sources/Subs-Attachments.php]: But [uksort](https://www.php.net/manual/en/function.uksort.php) sorts by comparing the keys instead of the values. Since the goal is to preserve the keys while sorting by comparing values, I think [uasort](https://www.php.net/manual/en/function.uasort.php) is the function you want.

File: Sources/Subs-Attachments.php [hunk 3]
```diff
@@ -1108,33 +1096,32 @@ function getAttachMsgInfo($attachID)
...
-				a.id_attach, a.id_folder, a.id_msg, a.filename, a.file_hash, COALESCE(a.size, 0) AS filesize, a.downloads, a.approved, m.id_topic AS topic, m.id_board AS board,
+				a.id_attach, a.id_folder, a.id_msg, a.filename, a.file_hash, COALESCE(a.size, 0) AS filesize, a.downloads, a.approved, m.id_topic AS topic, m.id_board AS board, m.id_member,
 				a.width, a.height' . (empty($modSettings['attachmentShowImages']) || empty($modSettings['attachmentThumbnails']) ? '' : ',
 				COALESCE(thumb.id_attach, 0) AS id_thumb, thumb.width AS thumb_width, thumb.height AS thumb_height') . '
 			FROM {db_prefix}attachments AS a' . (empty($modSettings['attachmentShowImages']) || empty($modSettings['attachmentThumbnails']) ? '' : '
 				LEFT JOIN {db_prefix}attachments AS thumb ON (thumb.id_attach = a.id_thumb)') . '
 				LEFT JOIN {db_prefix}messages AS m ON (m.id_msg = a.id_msg)
 			WHERE a.attachment_type = {int:attachment_type}
-				' . (!empty($msgID) ? 'AND a.id_msg = {int:message_id}' : '') . '',
+				AND a.id_msg ' . (!empty($context['preview_message']) ? 'IN (0, {int:message_id})' : 'AND a.id_msg = {int:message_id}'),
```
Comment (Sesquipedalian) [inline Sources/Subs-Attachments.php]: e1adb58 removed the useless trailing empty string, but this version still has the `AND a.id_msg ` part twice when `$context['preview_message']` is empty.

**Review by Sesquipedalian — CHANGES_REQUESTED** [review]

**Review by Sesquipedalian — APPROVED** [review]
