### PR TITLE
Shows search results and improves code separation between search APIs and search admin action

### LINKED ISSUE #8159: [3.0]: Search results are not showing
### Basic Information

Run any search, and the results are not displayed.

### Steps to reproduce

1. Run any search.

### Expected result

Search results are displayed.

### Actual result

Search results are not displayed.

### Version/Git revision

3.0 Alpha 1

### Database Engine

All

### Database Version

_No response_

### PHP Version

_No response_

### Logs

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Sesquipedalian**
Fixes #8159

Also disentangles methods and settings for specific search APIs from the code in SMF\Actions\Admin\Search.

### CODE REVIEW

File: Sources/Search/APIs/Custom.php [hunk 1]
```diff
@@ -337,6 +364,377 @@ public function postModified(array &$msgOptions, array &$topicOptions, array &$p
 			}
 		}
 	}
+
+	/**
+	 * {@inheritDoc}
+	 */
+	public function postRemoved(int $id_msg): void
```
Comment (live627) [inline Sources/Search/APIs/Custom.php:373]: this should be added to `supportsMethod()`

Comment (Sesquipedalian) [reply Sources/Search/APIs/Custom.php:373]: Good catch

Comment (live627) [reply Sources/Search/APIs/Custom.php:373]: Looking further into this confusing mess, tit appears as if it returns  false, it bubbles up to the parent

https://github.com/SimpleMachines/SMF/blob/b11d8c4178b3d8e18a5243c33174524d216b8e4e/Sources/Search/APIs/Custom.php#L91-L99

This interface violates the Interface Segregation Principle. Perhaps we can break out the post and the topic methods into their own interfaces.

File: Sources/Search/APIs/Custom.php [hunk 2]
```diff
@@ -27,6 +32,24 @@
...
+
+	/**
+	 * @var array
+	 *
+	 * Sub-actions to add for SMF\Actions\Admin\Search::$subactions.
+	 */
+	public static array $admin_subactions = [
+		'createmsgindex' => __CLASS__ . '::build',
+		'removecustom' => __CLASS__ . '::remove',
+	];
```
Comment (live627) [inline Sources/Search/APIs/Custom.php:47]: Can this be a method?

I have these three methods in my  custom action interface. Perhaps they could be of use.

	public function addSubAction(string $sa, callable $cb): void;
	public function hasSubAction(string $sa): bool;
	public function callSubAction(string $sa): void;

File: Sources/Search/APIs/Custom.php (hunk 1 above)
Comment (Sesquipedalian) [reply Sources/Search/APIs/Custom.php:373]: > confusing mess

Indeed. The search APIs date way back to the early days of SMF 2.1, and they were less than rigorously structured, to say the least. This PR is working toward cleaning up the mess, but there's still going to be more to do after this.

File: Sources/Search/APIs/Custom.php (hunk 2 above)
Comment (Sesquipedalian) [reply Sources/Search/APIs/Custom.php:47]: 🤔 Maybe. Those methods do look interesting. 

Since you already have code and an idea for this, how about I just leave it to you to make a PR implementing that idea at your leisure after this is merged?
