### PR TITLE
Fixes Issue #7655: Correct notification mail template for "Immediate"

### LINKED ISSUE #7655: Notification mail template is inconsistent with "Immediately" notification setting
#### Description

Continued from https://www.simplemachines.org/community/index.php?topic=584475.0

Even if you set the notification settings to "Immediately" rather than "Immediately - First time only", the mail template says the following:

> More replies may be posted, but you won't receive any more notifications for this topic until you visit it.

I certainly got a bit confused because I got more than one mail, but I also didn't get a mail for every reply. This sentence should probably be omitted from the mail if notifications are set to "Immediate". Maybe it should also mention that not every reply will trigger an immediate mail notification, as SMF tries to avoid being too spammy.

### PR DESCRIPTION
**Pull request by nc3man**
The value of $frequency must be checked in order to select the correct message based on user notification frequency setting

### CODE REVIEW

**Comment by nc3man** [comment]
Sorry for the first bolluxed PR attempt. Thank you for closing that, although I see I could have done it as well. I was able to learn a little more and was able to rebase my repo by removing all 3 previous commits.
```
git reset --hard 7c7593518
git push --force origin HEAD:release-2.1
```
where 7c7593518 was the SHA in reflog prior to the first commit. Learned something :). I then committed the simple one line change. 
Thanks for your patience.

File: Sources/tasks/CreatePost-Notify.php [hunk 1]
```diff
@@ -529,7 +529,7 @@ protected function handleWatchedNotifications()
 
 				$content_type = 'board';
 
-				$message_type = !empty($frequency) ? 'notify_boards_once' : 'notify_boards';
+				$message_type = (!empty($frequency) && $frequency==2) ? 'notify_boards_once' : 'notify_boards';
```
Comment (live627) [inline Sources/tasks/CreatePost-Notify.php]:
```suggestion
				$message_type = !empty($frequency) && $frequency == 2 ? 'notify_boards_once' : 'notify_boards';
```

**Review by live627 — CHANGES_REQUESTED** [review]
just some formatting
