### PR TITLE
[3.0] Various Fixes

### LINKED ISSUE #8013: [3.0]: TypeError on export profile data
### Basic Information

Error: `hash_hmac(): Argument #2 ($data) must be of type string, int given`
File: ExportProfileData.php
Line: 1506

### Steps to reproduce

1. Open own profile
2. Try to export profile data

### Expected result

_No response_

### Actual result

_No response_

### Version/Git revision

3.0 Alpha 1

### Database Engine

MySQL

### Database Version

10.11.6-MariaDB

### PHP Version

8.0.30

### Logs

_No response_

### Additional Information

sshot-17

### LINKED ISSUE #8014: [3.0]: TypeError on adding new languages
### Basic Information

Error: `Argument #1 ($array) must be of type array, string given, called in Sources\PackageManager\XmlArray.php on line 233
File: XmlArray.php

### Steps to reproduce

1. Go to Languages -> Add language
2. Try to add a new language

### Expected result

_No response_

### Actual result

_No response_

### Version/Git revision

3.0 Alpha 1

### Database Engine

MySQL

### Database Version

10.11.6-MariaDB

### PHP Version

8.0.30

### Logs

_No response_

### Additional Information

sshot-18

### PR DESCRIPTION
**Pull request by jdarwood007**
- Fix XmlArray to return false when we get an empty string for $action in `exist` method.  Fixes #8014
- Various errors were discovered running the export profile.  Fixes #8013 
- Alert needs to check `member_started` and member_name are initialized before usage.
- Various casting errors
- Actions/Feed. was using `$row` instead of `$profile` logic.

### CODE REVIEW

File: Sources/Actions/Feed.php [hunk 1]
```diff
@@ -1761,12 +1761,12 @@ public function getXmlProfile(): array
...
 					'tag' => 'last-login',
 					'attributes' => ['label' => Lang::$txt['lastLoggedIn'], 'UTC' => Time::gmstrftime('%F %T', $profile['last_login_timestamp'])],
-					'content' => Time::create('@' . $row['last_login_timestamp'], new \DateTimeZone(Config::$modSettings['default_timezone']))->format(null, false),
+					'content' => Time::create('@' . User::$me->last_login_timestamp, new \DateTimeZone(Config::$modSettings['default_timezone']))->format(null, false),
 				],
 				[
 					'tag' => 'registered',
 					'attributes' => ['label' => Lang::$txt['date_registered'], 'UTC' => Time::gmstrftime('%F %T', $profile['registered_timestamp'])],
-					'content' => Time::create('@' . $row['registered_timestamp'], new \DateTimeZone(Config::$modSettings['default_timezone']))->format(null, false),
+					'content' => Time::create('@' . User::$me->last_login_timestamp, new \DateTimeZone(Config::$modSettings['default_timezone']))->format(null, false),
```
Comment (dragomano) [inline Sources/Actions/Feed.php]: Maybe `User::$me->registered_timestamp`?

File: Sources/Tasks/ExportProfileData.php [hunk 2]
```diff
@@ -1883,7 +1883,7 @@ public static function add_dtd(
 	 * Adjusts some parse_bbc() parameters for the special case of HTML and
 	 * XML_XSLT exports.
 	 */
-	public static function pre_parsebbc_html(string &$message, array &$smileys, string &$cache_id, array &$parse_tags, array &$cache_key_extras): void
+	public static function pre_parsebbc_html(string &$message, bool &$smileys, string &$cache_id, array &$parse_tags, array &$cache_key_extras): void
```
Comment (dragomano) [inline Sources/Tasks/ExportProfileData.php:1886]: In the `pre_parsebbc_xml` method that located below, you also need to use the `bool` type for `&$smileys`. Or not?

File: Sources/Actions/Feed.php (hunk 1 above)
Comment (jdarwood007) [reply Sources/Actions/Feed.php]: Also looks like it should be $profile. Thanks!

File: Sources/Tasks/ExportProfileData.php (hunk 2 above)
Comment (jdarwood007) [reply Sources/Tasks/ExportProfileData.php:1886]: Correct.  I will send it here, but I believe I have this fixed in my strict types PR.  Lots of issues found with ExportProfileData and other tasks.

**Review by tyrsson — APPROVED** [review]
