### PR TITLE
[3.0] Remove convert to text option

### LINKED ISSUE #6763: Convert to TEXT fails if data too long
#### Description
The Forum Maintenance function to convert from MEDIUMTEXT to TEXT claims it will truncate values in order to complete:
image

But it doesn't, instead, it errors out:
image

I think this is a byproduct of converting SMF to strict mode.  Without strict mode, it will truncate.  It needs to explicitly truncate now.

### Steps to reproduce
1.  Use the Admin | Maintenance | Database | Convert to MEDIUMTEXT function
2.  Add data that exceeds 65535 bytes
3.  Use the Admin | Maintenance | Database | Convert to TEXT function

### Environment (complete as necessary)
- Version/Git revision: Today
- Database Type: mysql
- Database Version: 5.7
- PHP Version: 7.4

### Additional information/references
Reported on forum here: https://www.simplemachines.org/community/index.php?topic=577205.msg4089531#msg4089531

### PR DESCRIPTION
**Pull request by jdarwood007**
If an admin is already on medium text, do not give the option to convert back to text.  Difficulty arises ensuring this doesn't truncate or error our.

Fixes #6763

### CODE REVIEW

File: Languages/en_US/ManageMaintenance.php [hunk 1]
```diff
@@ -210,17 +210,9 @@
 $txt['maintain_members_choose'] = 'Selected Groups';
 $txt['maintain_members_confirm'] = 'Are you sure you really want to delete these member accounts?-n-This cannot be undone!';
 
-$txt['text_title'] = 'Convert to TEXT';
 $txt['mediumtext_title'] = 'Convert to MEDIUMTEXT';
-$txt['mediumtext_introduction'] = 'The default messages table can contain posts up to a size of 65535 characters, in order be able to store bigger texts the column must be converted to "MEDIUMTEXT". It is also possible to revert the column back to TEXT (that operation would reduce the space occupied), but <strong>only if</strong> none of the posts in your database exceed the size of 65535 characters. This condition will be verified before the conversion.';
+$txt['mediumtext_introduction'] = 'The default messages table can contain posts up to a size of 65535 characters, in order be able to store bigger texts the column must be converted to "MEDIUMTEXT". This operation is not reversible and manually attempting to do so may result in data loss.';
```
Comment (Sesquipedalian) [inline Languages/en_US/ManageMaintenance.php]:
```suggestion
$txt['mediumtext_introduction'] = 'The default messages table can contain posts up to a size of 65535 characters, in order be able to store bigger texts the column must be converted to "MEDIUMTEXT". This operation is not reversible.';
```

Since we don't offer the option to revert the change, that's all we really need to say. Anyone trying to do it manually will have to use raw SQL queries, which means they can and should know what they are doing and what the consequences are.

File: Sources/Actions/Admin/Maintenance.php [hunk 2]
```diff
@@ -1252,10 +1250,10 @@ public function entitiesToUnicode(): void
 	}
 
 	/**
-	 * Convert the column "body" of the table {db_prefix}messages from TEXT to MEDIUMTEXT and vice versa.
+	 * Convert the column "body" of the table {db_prefix}messages from TEXT to MEDIUMTEXT.
 	 * It requires the admin_forum permission.
 	 * This is needed only for MySQL.
-	 * During the conversion from MEDIUMTEXT to TEXT it check if any of the posts exceed the TEXT length and if so it aborts.
+	 * No longer do we support TEXT To MEDIUMTEXT.
```
Comment (Sesquipedalian) [inline Sources/Actions/Admin/Maintenance.php]:
```suggestion
	 * We no longer support reverting from MEDIUMTEXT back to TEXT.
```

File: Themes/default/ManageMaintenance.template.php [hunk 3]
```diff
@@ -574,46 +573,4 @@ function template_convert_entities()
...
-			<form action="', Config::$scripturl, '?action=admin;area=maintain;sa=database;activity=convertmsgbody" method="post" accept-charset="UTF-8">
-			<hr>
-			<input type="hidden" name="', Utils::$context['session_var'], '" value="', Utils::$context['session_id'], '">
-			<input type="hidden" name="', Utils::$context['admin-maint_token_var'], '" value="', Utils::$context['admin-maint_token'], '">
-			<input type="submit" name="do_conversion" value="', Lang::getTxt('entity_convert_proceed', file: 'ManageMaintenance'), '" class="button">
-			</form>
-		</div><!-- .windowbg -->
-	</div><!-- #manage_maintenance -->';
-}
+}
```
Comment (Sesquipedalian) [inline Themes/default/ManageMaintenance.template.php]: Please restore the final newline.

**Review by Sesquipedalian — CHANGES_REQUESTED** [review]

**Review by Sesquipedalian — APPROVED** [review]
