### PR TITLE
This should fix #3294

### LINKED ISSUE #3294: Error when viewed as guest.
Just upgraded from 2.1 beta 2 which was working fine.  to the latest files (beta 3) from the repo. Now when viewing site as guest I get a error on page.   Obviously I was logged in as admin while upgrading, and site worked perfectly while I was logged in, no errors. Now session has expired I can no longer log in.

"Database Error
Please try again. If you come back to this error screen, report the error to an administrator."

And these three errors in the error log every time you view the index page.as guest.

Type of error: Database
Database Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.156.188 BETWEEN bi.ip_low and bi.ip_high OR )' at line 6 
http://cctestsite.info/testsite3/index.php? 
File: /Sources/Security.php
Line: 226 

Type of error: General
 2: inet_pton() [<a href='function.inet-pton'>function.inet-pton</a>]: Unrecognized address  
http://cctestsite.info/testsite3/index.php? 
File: /home2/cameracr/public_html/cctestsite.info/testsite3/Sources/Security.php
Line: 1274 

Type of error: Undefined
 8: Undefined variable: bin 
 http://cctestsite.info/testsite3/index.php?File: /home2/cameracr/public_html/cctestsite.info/testsite3/Sources/Subs.php
Line: 4787

### PR DESCRIPTION
**Pull request by live627**

### CODE REVIEW

File: Sources/Subs.php [hunk 1]
```diff
@@ -5120,25 +5120,7 @@ function smf_chmod($file, $value = 0)
...
-			return false;
-	}
-	else
-	{
-		if (@inet_pton($IPString))
-			return true;
-		else
-			return false;
-	}
+	return filter_var($IPString,FILTER_VALIDATE_IP);
```
Comment (albertlast) [inline Sources/Subs.php:5123]: Filter_var is an optional(default on) addon in php,
you are sure about to do this without backup?
And filter_var return a string and not boolean,
i'm not sure if this harm somewhere or not.
I think the min is to update the function discription.
