### PR TITLE
Fix deleted custom field values

### LINKED ISSUE #5379: Not able to delete some profile fields
#### Description
--Description Here--
On my test account I had no problems adding and deleting the skype-field.
A member joined and tried to delete his Skype, but after "change profile" and going back to profile overview you still see the skype-icon. Once back on the forum profile the skype name is back.
Tried several times to delete it, turned the profile field on and off, but it is impossible (by some accounts) to delete the skype-name once filled in.

### Steps to reproduce
1. Add skypename in forum profile and confirm/change profile
2. Delete the name (empty textbox) and confirm/change profile -> view profile overview: skype not deleted. -> back to forum profile: Skype name is not deleted.

### Environment (complete as necessary)
- Version/Git revision: RC1
- Database Type: MariaDB
- Database Version: 10.1.37-MariaDB
- PHP Version: 5.6.39

### PR DESCRIPTION
**Pull request by SychO9**
Fixes #5379

### CODE REVIEW

File: Sources/Profile-Modify.php [hunk 1]
```diff
@@ -1342,13 +1342,14 @@ function makeCustomFieldChanges($memID, $area, $sanitize = true, $returnErrors =
...
 			);
 		if (!empty($deletes))
-			$smcFunc['db_query']('', '
-				DELETE FROM {db_prefix}themes
-				WHERE id_theme = {int:id_theme} AND
-					variable = {string:variable} AND
-					id_member = {int:id_member}',
-				$deletes
-			);
+			foreach($deletes as $delete)
```
Comment (Sesquipedalian) [inline Sources/Profile-Modify.php]: Nit: SMF's coding style prefers a space between the `foreach` and the `(`.

File: Sources/Profile-Modify.php [hunk 2]
```diff
@@ -1342,13 +1342,14 @@ function makeCustomFieldChanges($memID, $area, $sanitize = true, $returnErrors =
...
+				$smcFunc['db_query']('', '
+					DELETE FROM {db_prefix}themes
+					WHERE id_theme = {int:id_theme} AND
+						variable = {string:variable} AND
```
Comment (Sesquipedalian) [inline Sources/Profile-Modify.php]: Nit: SMF's coding style prefers the `AND` to be placed at the start of the next line rather than at the end of the previous line.

**Review by Sesquipedalian — CHANGES_REQUESTED** [review]
Just needs some minor stylistic adjustments.

**Review by Sesquipedalian — APPROVED** [review]
