### PR TITLE
Registration password length error message fix. Fixes #6215

### LINKED ISSUE #6215: Registration password length language error
#### Description
image

### Steps to reproduce
1. Sign up for account
2. Put password length less than the minimum required by your security settings.
3. Submit registration.

### Environment (complete as necessary)
- Version/Git revision: 2.1 latest
- Database Type:mysql
- Database Version:mariadb
- PHP Version:7.4

### Additional information/references

### PR DESCRIPTION
**Pull request by Butterflysaway**
Fixes #6215

### CODE REVIEW

File: Sources/Subs-Members.php [hunk 1]
```diff
@@ -506,7 +506,12 @@ function registerMember(&$regOptions, $return_errors = false)
 
 		// Password isn't legal?
 		if ($passwordError != null)
-			$reg_errors[] = array('lang', 'profile_error_password_' . $passwordError);
+		{
+			$errorCode = array('lang', 'profile_error_password_' . $passwordError, false);
+			if($passwordError == 'short')
```
Comment (live627) [inline Sources/Subs-Members.php]: Can you please add a space after the if, Allman style?

**Review by live627 — CHANGES_REQUESTED** [review]
Can you please add a sign-off to all of your future commits?

**Comment by Butterflysaway** [comment]
@live627 done.

**Review by live627 — APPROVED** [review]
