### PR TITLE
[3.0] Don't trust totalMembers

### LINKED ISSUE #8841: [3.0|2.1]: Admin member list omits inactive members
### Basic Information

https://www.simplemachines.org/community/index.php?topic=592451.0

### Steps to reproduce
According to the topic:
1. Log in as an admin user in a forum migrated from version 2.0.19 to 2.1.6.
2. Navigate to Admin > Members > View all Members.
3. Observe that inactive members are missing.

### Expected result

The admin member list is supposed to display every account on the forum regardless of activation status.

### Version/Git revision

2.1.6

### PR DESCRIPTION
**Pull request by jdarwood007**
Fixes #8841

### CODE REVIEW

File: Sources/Actions/Admin/Members.php [hunk 1]
```diff
@@ -1453,22 +1453,15 @@ public static function list_getMembers(int $start, int $items_per_page, string $
...
-			);
-			list($num_members) = Db::$db->fetch_row($request);
-			Db::$db->free_result($request);
-		}
+		$request = Db::$db->query(
+			'SELECT COUNT(*)
+			FROM {db_prefix}members AS mem
+			WHERE ' . $where,
+			array_merge($where_params, [
+			]),
```
Comment (Sesquipedalian) [inline Sources/Actions/Admin/Members.php]:
```suggestion
			$where_params,
```

Not much point merging an empty array. 🙂

**Review by Sesquipedalian — CHANGES_REQUESTED** [review]

**Review by Sesquipedalian — APPROVED** [review]
