### PR TITLE
Call helper

### LINKED ISSUE #1895: call static method in ManageSettings.php
SMF 2.0.8
php 5.4

error: Fatal error: Call to undefined function MyClass::mystaticmethod() in ...\Sources\ManageSettings.php on line 198

find:

``` php
    // Call the right function for this sub-acton.
    $subActions[$_REQUEST['sa']]();
```

replace:

``` php
    $func = strpos($subActions[$_REQUEST['sa']], '::') !== false ? explode('::', $subActions[$_REQUEST['sa']]) : $subActions[$_REQUEST['sa']];
    // Call the right function for this sub-acton.
    if (is_array($func))
        call_user_func($func);
    else
        $func();
```

### PR DESCRIPTION
**Pull request by MissAllSunday**
Another round for finding calls to sub-actions.
- My other search missed some variants like $sub_action and $subaction thus a few other places were still using the string directly fixes #1895  /me hopes...
- call_helper() will now return a boolean false/log an error if the given string cannot produce a callable var.
- Removes some is_callable() checks and instead it places an !empty()

### CODE REVIEW

File: Sources/Admin.php [hunk 1]
```diff
@@ -922,7 +922,7 @@ function AdminLogs()
 
 	call_integration_hook('integrate_manage_logs', array(&$log_functions));
 
-	$sub_action = isset($_REQUEST['sa']) && isset($log_functions[$_REQUEST['sa']]) && empty($log_functions[$_REQUEST['sa']]['disabled']) ? $_REQUEST['sa'] : 'errorlog';
+	$subActions = isset($_REQUEST['sa']) && isset($log_functions[$_REQUEST['sa']]) && empty($log_functions[$_REQUEST['sa']]['disabled']) ? $_REQUEST['sa'] : 'errorlog';
```
Comment (live627) [inline Sources/Admin.php]: Shouldn't this be singular?
