### PR TITLE
Reduce the amount of attachment queries fixes #5492

### LINKED ISSUE #5492: Recent topic + attachment to many queries
#### Description
When you enable recent topic and got a normal(limited) user,
than every attachment in a message create 4 additional queries

### Steps to reproduce
1. enable recent messages
2. look how many queries are used on index page (refresh so long until you reached the lowest number)
3. add a post with attachment
4. go to the index again (like step 2) and refresh so long you get the lowest number of quries

The delta should be 4 queries and this number get higher per post with attachment

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references
```
      SELECT a.id_msg AS msg, m.id_topic AS topic, m.id_board AS board
      FROM smf_attachments AS a
         LEFT JOIN smf_messages AS m ON (m.id_msg = a.id_msg)
      WHERE id_attach = 34
      LIMIT 1
   in ...\Sources\Subs-Attachments.php line 1071, which took 0.00052714 seconds at 0.0657959 into request.

      SELECT MIN(bp.add_deny) AS add_deny
      FROM smf_boards AS b
         INNER JOIN smf_board_permissions AS bp ON (bp.id_profile = b.id_profile)
         LEFT JOIN smf_moderators AS mods ON (mods.id_board = b.id_board AND mods.id_member = 2)
         LEFT JOIN smf_moderator_groups AS modgs ON (modgs.id_board = b.id_board AND modgs.id_group IN (2, 7))
      WHERE b.id_board IN (92)
         AND bp.id_group IN (2, 7, 3)
         AND bp.permission IN ('view_attachments')
         AND (mods.id_member IS NOT NULL OR modgs.id_group IS NOT NULL OR bp.id_group != 3)
      GROUP BY b.id_board
   in ...\Sources\Security.php line 944, which took 0.00092292 seconds at 0.06647396 into request.

         SELECT
            a.id_attach, a.id_folder, a.id_msg, a.filename, a.file_hash, COALESCE(a.size, 0) AS filesize, a.downloads, a.approved, m.id_topic AS topic, m.id_board AS board,
            a.width, a.height,
            COALESCE(thumb.id_attach, 0) AS id_thumb, thumb.width AS thumb_width, thumb.height AS thumb_height
         FROM smf_attachments AS a
            LEFT JOIN smf_attachments AS thumb ON (thumb.id_attach = a.id_thumb)
            LEFT JOIN smf_messages AS m ON (m.id_msg = a.id_msg)
         WHERE a.attachment_type = 0
            AND a.id_msg = 1194699
   in ...\Sources\Subs-Attachments.php line 1111, which took 0.00060296 seconds at 0.06750298 into request.

      SELECT MIN(bp.add_deny) AS add_deny
      FROM smf_boards AS b
         INNER JOIN smf_board_permissions AS bp ON (bp.id_profile = b.id_profile)
         LEFT JOIN smf_moderators AS mods ON (mods.id_board = b.id_board AND mods.id_member = 2)
         LEFT JOIN smf_moderator_groups AS modgs ON (modgs.id_board = b.id_board AND modgs.id_group IN (2, 7))
      WHERE b.id_board IN (92)
         AND bp.id_group IN (2, 7, 3)
         AND bp.permission IN ('view_attachments')
         AND (mods.id_member IS NOT NULL OR modgs.id_group IS NOT NULL OR bp.id_group != 3)
      GROUP BY b.id_board
   in ...\Sources\Security.php line 944, which took 0.00058889 seconds at 0.06825495 into request.

### PR DESCRIPTION
**Pull request by albertlast**
It's redurce the amount of to one for all attachment.

Idea is to "prepare" the attachment api with the needed data.

@Sesquipedalian i guess you should look into this.

issue: #5492

in my test env the amount of quries get down from 28 to 15.

### CODE REVIEW

File: Sources/Subs-Attachments.php [hunk 1]
```diff
@@ -1126,11 +1140,14 @@ function getAttachMsgInfo($attachID)
...
 {
-	global $context, $modSettings, $smcFunc, $user_info;
+	global $context, $modSettings, $smcFunc, $user_info, $cacheMsgID;
 	static $attached = array();
 
 	if (!isset($attached[$msgID]))
 	{
+		if (empty($cacheMsgID[$msgID]))
+			prepareAttachsByMsg ([$msgID]);
+/*
```
Comment (MissAllSunday) [inline Sources/Subs-Attachments.php]: I know our minimum version supports short syntax for arrays [] but to keep some normalization and consistency with the rest of the code please use the old array format

File: Sources/Subs-Attachments.php [hunk 2]
```diff
@@ -1092,11 +1092,25 @@ function getRawAttachInfo($attachIDs)
...
+	foreach ($cacheMsgID as $msgRows)
+	{
+		if (empty($msgRows[$attachID]))
+			continue;
+
+		$row = array(
+			'msg' => $msgRows[$attachID]['id_msg'],
+			'topic' => $msgRows[$attachID]['topic'],
+			'board' => $msgRows[$attachID]['board'],
+			);
```
Comment (Sesquipedalian) [inline Sources/Subs-Attachments.php]: Please reduce indentation by one tab.

File: Sources/Subs-Attachments.php [hunk 3]
```diff
@@ -1126,35 +1140,23 @@ function getAttachMsgInfo($attachID)
...
-				LEFT JOIN {db_prefix}messages AS m ON (m.id_msg = a.id_msg)
-			WHERE a.attachment_type = {int:attachment_type}
-				AND a.id_msg ' . (!empty($context['preview_message']) ? 'IN (0, {int:message_id})' : '= {int:message_id}'),
-			array(
-				'message_id' => $msgID,
-				'attachment_type' => 0,
-			)
-		);
+		if (empty($cacheMsgID[$msgID]))
+			prepareAttachsByMsg (array($msgID));
```
Comment (Sesquipedalian) [inline Sources/Subs-Attachments.php]: Please remove unnecessary whitespace:
```
prepareAttachsByMsg(array($msgID));
```

File: Sources/Subs-Attachments.php [hunk 4]
```diff
@@ -1346,4 +1348,50 @@ function loadAttachmentContext($id_msg, $attachments)
...
+			)
+		);
+		$temp = array();
+		$rows = $smcFunc['db_fetch_all']($request);
+		$smcFunc['db_free_result']($request);
+
+		foreach ($rows as $value)
+		{
+			if(empty($cacheMsgID[$value['id_msg']]))
+				$cacheMsgID[$value['id_msg']] = [];
```
Comment (Sesquipedalian) [inline Sources/Subs-Attachments.php]:
```
$cacheMsgID[$value['id_msg']] = array();
```

File: Sources/Subs-Attachments.php [hunk 5]
```diff
@@ -1346,4 +1348,50 @@ function loadAttachmentContext($id_msg, $attachments)
...
+ * @return void.
+ */
+function prepareAttachsByMsg($msgIDs)
+{
+	global $context, $modSettings, $smcFunc, $user_info, $cacheMsgID;
+	if(!isset($cacheMsgID))
+		$cacheMsgID = array();
+
+	// remove all $msgIDs which we already cached
+	$msgIDs = array_flip(array_diff_key(array_flip($msgIDs), $cacheMsgID)) ;
```
Comment (Sesquipedalian) [inline Sources/Subs-Attachments.php:1366]: This works, but it would be more efficient to use the following.
```
$msgIDs = array_diff($msgIDs, array_keys($cacheMsgID));
```

Also, you could put an `else` before this line, because there is no need to do it at all if `$cacheMsgID` is empty.

File: Sources/Subs-Attachments.php [hunk 6]
```diff
@@ -1346,4 +1348,50 @@ function loadAttachmentContext($id_msg, $attachments)
...
+ * prepare the Attachment api for all messages
+ *
+ * @param int array $msgIDs the message ID to load info from.
+ *
+ * @return void.
+ */
+function prepareAttachsByMsg($msgIDs)
+{
+	global $context, $modSettings, $smcFunc, $user_info, $cacheMsgID;
+	if(!isset($cacheMsgID))
```
Comment (Sesquipedalian) [inline Sources/Subs-Attachments.php:1362]: Please add a line break above this line.

File: Sources/Subs-Recent.php [hunk 7]
```diff
@@ -51,8 +51,29 @@ function getLastPosts($latestPostOptions)
 			'is_approved' => 1,
 		)
 	);
+
+	$rows = $smcFunc['db_fetch_all']($request);
+
+	// BBC and the entire attachments feature is enabled
+	$disabled = array();
+
+	$temp = !empty($modSettings['disabledBBC']) ? explode(',', strtolower($modSettings['disabledBBC'])) : [];
```
Comment (Sesquipedalian) [inline Sources/Subs-Recent.php]:
```
$temp = !empty($modSettings['disabledBBC']) ? explode(',', strtolower($modSettings['disabledBBC'])) : array();
```

**Review by Sesquipedalian — CHANGES_REQUESTED** [review]
Two main changes requested:

1. When I ran a test of this code, I noticed that two very similar queries were run when displaying a topic with attachments: the new one in `prepareAttachsByMsg()` and another in Display.php here:
https://github.com/SimpleMachines/SMF2.1/blob/967873f3130809fda9dffe19055d01fd348aa317/Sources/Display.php#L1159-L1197
I think you can remove the code you've added to Display.php and instead just replace the query that already exists in Display.php with a call to `prepareAttachsByMsg()`.

2. The structure you use in your new `$cacheMsgID` variable is very similar to the one already being used for `$context['loaded_attachments']`. So, if you use `$context['loaded_attachments']` for this task, that would be more efficient on memory usage by avoiding duplicate data. It will also make it easier to implement my first requested change.

The rest of my change requests here are for minor fixes to formatting and style.

**Comment by albertlast** [comment]
1. this is no new issue, this is already exists.
the code is written to be used in any places like in the recent thing
so i see no chance to change it,
like always feel free to change it after ward.

2. the big different is that here is not authority checks are done or
any other higher logic, it's hold only the data for the case that it's needed.
So i could move the data to context but not into the key.

File: Sources/Subs-Attachments.php (hunk 5 above)
Comment (albertlast) [reply Sources/Subs-Attachments.php:1366]: ``$msgIDs = array_diff($msgIDs, array_keys($cacheMsgID));``
since the $cacheMsgID is possibe bigger of memory footprint and got a more complex structur,
i choose the other way.

**Comment by Sesquipedalian** [comment]
> so i see no chance to change it,
> like always feel free to change it after ward.

I did, and then I found more efficiencies and some code that we could remove, so I did that too in a3460e3 before merging.

**Comment by albertlast** [comment]
Yes you changes make sense,
beside of the sort thing,
but for this you need a "bigger" knowledg about attachment stuff which i doesn't had and
the scope of the pr over extend.
