### PR TITLE
Show embedded images

### LINKED ISSUE #6464: Embedded attached images are not shown
#### Description
If the setting Display image attachments as pictures under post is disabled
embedded attached images does only show the filename.

### Steps to reproduce
1. Disable the setting Display image attachments as pictures under post
2. Upload an image and embed it in the message.
3. The image is not shown in the message, only the filename is shown.

### Environment (complete as necessary)
- Version/Git revision: 9f42c5fdf
- Database Type: MySQL
- Database Version:
- PHP Version: 5.6

### Additional information/references

### PR DESCRIPTION
**Pull request by BrickOzp**
Show embedded images even if the setting "Display image attachments as pictures under post" is disabled.
    
Fixes #6464
    
Signed-off-by: Oscar Rydhé oscar.rydhe@gmail.com

### CODE REVIEW

File: Sources/Subs.php [hunk 1]
```diff
@@ -1434,27 +1434,17 @@ function parse_bbc($message, $smileys = true, $cache_id = '', $parse_tags = arra
...
-
-							if ($currentAttachment['thumbnail']['has_thumb'] && empty($params['{width}']) && empty($params['{height}']))
-								$returnContext .= '<a href="' . $currentAttachment['href'] . ';image" id="link_' . $currentAttachment['id'] . '" onclick="' . $currentAttachment['thumbnail']['javascript'] . '"><img src="' . $currentAttachment['thumbnail']['href'] . '"' . $alt . $title . ' id="thumb_' . $currentAttachment['id'] . '" class="atc_img"></a>';
+							if (empty($params['{width}']) && empty($params['{height}']))
+								$returnContext .= '<img src="' . $currentAttachment['href'] . '"' . $alt . $title . ' class="bbc_img"></a>';
 							else
-								$returnContext .= '<img src="' . $currentAttachment['href'] . ';image"' . $alt . $title . $width . $height . ' class="bbc_img"/>';
+							{
+                                $width = !empty($params['{width}']) ? ' width="' . $params['{width}'] . '"': '';
+							    $height = !empty($params['{height}']) ? 'height="' . $params['{height}'] . '"' : '';
```
Comment (live627) [inline Sources/Subs.php]:
```suggestion
								$width = !empty($params['{width}']) ? ' width="' . $params['{width}'] . '"': '';
								$height = !empty($params['{height}']) ? 'height="' . $params['{height}'] . '"' : '';
```

File: Sources/Subs-Attachments.php [hunk 2]
```diff
@@ -1164,7 +1164,7 @@ function loadAttachmentContext($id_msg, $attachments)
 				'byte_size' => $attachment['filesize'],
 				'href' => $scripturl . '?action=dlattach;topic=' . $attachment['topic'] . '.0;attach=' . $attachment['id_attach'],
 				'link' => '<a href="' . $scripturl . '?action=dlattach;topic=' . $attachment['topic'] . '.0;attach=' . $attachment['id_attach'] . '" class="bbc_link">' . $smcFunc['htmlspecialchars']($attachment['filename']) . '</a>',
-				'is_image' => !empty($attachment['width']) && !empty($attachment['height']) && !empty($modSettings['attachmentShowImages']),
+				'is_image' => !empty($attachment['width']) && !empty($attachment['height']) ,
```
Comment (live627) [inline Sources/Subs-Attachments.php]:
```suggestion
				'is_image' => !empty($attachment['width']) && !empty($attachment['height']),
```

**Review by live627 — CHANGES_REQUESTED** [review]
whitespace

**Review by live627 — APPROVED** [review]
