### PR TITLE
Use simple inserts

### LINKED ISSUE #6841: Export dir get created in wrong way/path
#### Description
Dunno which step the export dir get generated,
but my file path look like this now:
grafik
grafik

### Environment (complete as necessary)
- Version/Git revision: head
- Database Type: postgresql
- Database Version: 12
- PHP Version: 7.3.12

### PR DESCRIPTION
**Pull request by sbulen**
Fixes #6841 

Tested in both pg & mysql.  settings created properly & exports function properly.

### CODE REVIEW

File: other/upgrade_2-1_mysql.sql [hunk 1]
```diff
@@ -327,21 +327,10 @@ INSERT INTO {$db_prefix}settings (variable, value) VALUES ('defaultMaxListItems'
...
-		array('variable' => 'string', 'value' => 'string'),
-		$inserts,
-		array('variable')
-	);
----}
----#
+INSERT INTO {$db_prefix}settings (variable, value) VALUES ('export_dir', '{$boarddir}/exports');
+INSERT INTO {$db_prefix}settings (variable, value) VALUES ('export_expiry', '7');
+INSERT INTO {$db_prefix}settings (variable, value) VALUES ('export_min_diskspace_pct', '5');
+INSERT INTO {$db_prefix}settings (variable, value) VALUES ('export_rate', '250');
```
Comment (albertlast) [inline other/upgrade_2-1_mysql.sql:335]: ---# missing

File: other/upgrade_2-1_postgresql.sql [hunk 2]
```diff
@@ -496,21 +496,10 @@ INSERT INTO {$db_prefix}settings (variable, value) VALUES ('defaultMaxListItems'
...
-		array('variable' => 'string', 'value' => 'string'),
-		$inserts,
-		array('variable')
-	);
----}
----#
+INSERT INTO {$db_prefix}settings (variable, value) VALUES ('export_dir', '{$boarddir}/exports');
+INSERT INTO {$db_prefix}settings (variable, value) VALUES ('export_expiry', '7');
+INSERT INTO {$db_prefix}settings (variable, value) VALUES ('export_min_diskspace_pct', '5');
+INSERT INTO {$db_prefix}settings (variable, value) VALUES ('export_rate', '250');
```
Comment (albertlast) [inline other/upgrade_2-1_postgresql.sql:504]: ---# missing

**Review by albertlast — CHANGES_REQUESTED** [review]

**Comment by sbulen** [comment]
Changes made.  Good catch, thanks.

It is interesting that the upgrader didn't seem to care...

**Review by live627 — APPROVED** [review]
