### PR TITLE
Upgrader attachment & avatar fixes

### LINKED ISSUE #6942: Attachments failed eval
#### Description
During a CLI upgrade.  The upgrader crashed.  Restarting the upgrade resulted in this:

```
 *  +++  Adding more space to the mime_type column. done.
 +++  Converting legacy attachments.Error: Trying to access array offset on value of type bool File: /upgrade.php(2148) : eval()'d code Line: 65Error: Trying to access array offset on value of type bool File: /upgrade.php(2148) : eval()'d code Line: 65
```

As a temp patch, the following code was used in upgrade.php
```
				try
				{
					if(@eval('global $db_prefix, $modSettings, $smcFunc, $txt, $upcontext, $db_name; ' . $current_data))
						throw new ErrorException('eval error');
				}
				catch (Throwable $e) {
					$upcontext['error_message'] = 'Error in upgrade script ' . basename($filename) . ' on line ' . $line_number . '!' . $endl;
					if ($command_line)
						echo $upcontext['error_message'];
				}
				catch (ErrorException $e) {
					$upcontext['error_message'] = 'Error in upgrade script ' . basename($filename) . ' on line ' . $line_number . '!' . $endl;
					if ($command_line)
						echo $upcontext['error_message'];
				}
```

This let it continue.  But the original issue still exists.  There is nothing on that step that would eval on line 65 that results in a bool.

More research and testing will be needed.

This bug report essentially is two issues.

First is, we should have that try/catch, but disable it by default.  Its way late in 2.1's process to introduce that with little testing.  But by having it in there but disabled, we can have support enable it for upgrade issues if needed.

The second issue is why the attachments are failing or erroring out.

### Environment (complete as necessary)
- Version/Git revision: latet git
- Database Type: mysql
- Database Version: 5.7
- PHP Version: 7.4

### Additional information/references

### LINKED ISSUE #7082: Upgrader: Tries to delete custom_avatar directory
#### Description
I've never seen this one before...
`+++  Converting legacy attachments.Error: rmdir(yada/yada/custom_avatar): Directory not empty File: yada/yada\upgrade.php(2155) : eval()'d code Line: 31. done.
`

This particular run was via CLI, so I could see the error.  

### Steps to reproduce
1. Upgrade a 2.0 forum that already has a folder for custom_avatar

### Environment (complete as necessary)
- Version/Git revision:  Current
- Database Type:  mysql
- Database Version:  5.7
- PHP Version:  8.0

### Additional information/references
This is being run in a test wamp environment.  Initial suspicion is directory separators are confused, so it thinks that the folder names are different when they're not...

### PR DESCRIPTION
**Pull request by sbulen**
Fixes #7082 
Fixes #6942 

The attachment issues were only seen on restarts or reruns for forums with multiple attachment directories.  Just needed to keep better track of when it really completes successfully.  (json_done != attachments_done...)

We used to see 'failed to unserialize' for the attachment dir setting via CLI before, this PR cleans that up as well.  We only need to serialize it once...

The custom av issue only appeared if you had directory separators misaligned (e.g., \custom_avatar vs /custom_avatar...) - pretty rare, but I did in fact have it delete my custom_avatar directory multiple times during test...

### CODE REVIEW

**Comment by sbulen** [comment]
I still need to xlate this over to pg.  commit forthcoming.

**Review by jdarwood007 — APPROVED** [review]
The logic looks sound.  I haven't tested as I don't have the test database to verify it though.

**Comment by sbulen** [comment]
@jdarwood007 - any further input?  I'd like to get this merged.

File: other/upgrade_2-1_mysql.sql [hunk 1]
```diff
@@ -585,40 +589,42 @@ if (!empty($attachs))
...
+// Also ensure currentAttachmentUploadDir is set even for single directories
+// Make sure to do it in memory and in db...
+if (empty($modSettings['json_done']))
 {
-	// Serialized maybe?
-	$array = is_array($modSettings['attachmentUploadDir']) ? $modSettings['attachmentUploadDir'] : @unserialize($modSettings['attachmentUploadDir']);
-	if ($array !== false)
+	if (!is_array($modSettings['attachmentUploadDir']) && is_dir($modSettings['attachmentUploadDir']))
 	{
+		$modSettings['attachmentUploadDir'] = serialize(array(1 => $modSettings['attachmentUploadDir']));
```
Comment (jdarwood007) [inline other/upgrade_2-1_mysql.sql:599]: If we do this, do you need to set the current directory as well?

**Comment by jdarwood007** [comment]
The database I have is upgraded at this point.  But if this is clearing that error, it should be fine.

File: other/upgrade_2-1_mysql.sql (hunk 1 above)
Comment (sbulen) [reply other/upgrade_2-1_mysql.sql:599]: We're good here.  This is exactly what the existing logic does (the only change is serialize vs json, which was premature).

Comment (sbulen) [reply other/upgrade_2-1_mysql.sql:599]: Sorry if this is a dupe, GH seems to lose my comments....

I think we are good here.  Note this matches previous logic, the only difference is this is serial, not json, which was premature.

Comment (sbulen) [reply other/upgrade_2-1_mysql.sql:599]: Also note there is a subsequent step specifically to clean that up - "Fixing attachment directory setting..."
