### PR TITLE
Code BBC max height fix

### LINKED ISSUE #5318: Code tags layout
#### Description
Code layout doesn't have a limit and with long code we have a very long page.

### Environment (complete as necessary)
- Version/Git revision: SMF 2.1 RC1
- Database Type: All
- Database Version: All
- PHP Version: All

### Additional information/references
50677270-3ad7b800-0ff9-11e9-83c6-e4607bc6d420

### PR DESCRIPTION
**Pull request by SychO9**
Fixes #5318

### CODE REVIEW

**Comment by live627** [comment]
So what happens with a one-liner?

And jquery? I personally dislike jquery, but hey I'm probably the odd one out so sue me.

**Comment by SychO9** [comment]
> So what happens with a one-liner?

well the "Expand" button is hidden by default, the jquery code checks if the code's height exceeds the maximum height which is set and if so shows the button, so a one liner wouldn't have the button to expand.

> And jquery? I personally dislike jquery, but hey I'm probably the odd one out so sue me.

well... ¯\_(ツ)_/¯

File: Sources/Subs.php [hunk 1]
```diff
@@ -1304,7 +1304,7 @@ function parse_bbc($message, $smileys = true, $cache_id = '', $parse_tags = arra
 			array(
 				'tag' => 'code',
 				'type' => 'unparsed_content',
-				'content' => '<div class="codeheader"><span class="code floatleft">' . $txt['code'] . '</span> <a class="codeoperation smf_select_text">' . $txt['code_select'] . '</a></div><code class="bbc_code">$1</code>',
+				'content' => '<div class="codeheader"><span class="code floatleft">' . $txt['code'] . '</span> <a class="codeoperation smf_select_text">' . $txt['code_select'] . '</a> <a class="codeoperation smf_expand_code hidden" data-shrink-txt="' . $txt['code_shrink'] . '" data-expand-txt="' . $txt['code_expand'] . '">' . $txt['code_expand'] . '</a></div><code class="bbc_code">$1</code>',
```
Comment (Sesquipedalian) [inline Sources/Subs.php:1307]: Please add the same changes to the other version of the [code] BBC on this line:
https://github.com/SimpleMachines/SMF2.1/blob/1058026d83229306ce1b9999f3eb17fd0eef5e64/Sources/Subs.php#L1344

**Review by Sesquipedalian — CHANGES_REQUESTED** [review]

**Review by Sesquipedalian — APPROVED** [review]
