### PR TITLE
[2.1] Don't save a comment on non existent mod report

### LINKED ISSUE #7429: Moderator reported posts comments
#### Description
/index.php?action=moderate;area=reportedposts;sa=handlecomment;rid=xxxx
/Sources/Subs-ReportedContent.php (Line 609)

Type of error: General
Error messageSelect
8: Trying to access array offset on value of type bool

### Steps to reproduce
1. Unknown, in error log
2. 

### Environment (complete as necessary)
- Version/Git revision: 2.1.1
- Database Type:
- Database Version:
- PHP Version: 7.4

### Additional information/references
```
			'msg_id' => $report['id_msg'],
```

### PR DESCRIPTION
**Pull request by jdarwood007**
Fixes #7429

### CODE REVIEW

File: Sources/Subs-ReportedContent.php [hunk 1]
```diff
@@ -655,6 +655,9 @@ function saveModComment($report_id, $data)
 
 	$report = getReportDetails($report_id);
 
+	if (empty($report))
+		return false;
+
```
Comment (Sesquipedalian) [inline Sources/Subs-ReportedContent.php]: Should do this before trying to insert the comment.

**Review by Sesquipedalian — CHANGES_REQUESTED** [review]

**Review by Sesquipedalian — APPROVED** [review]
