### PR TITLE
[3.0] Don't save a comment on non existent mod report

### LINKED ISSUE #7429: Moderator reported posts comments
#### Description
/index.php?action=moderate;area=reportedposts;sa=handlecomment;rid=xxxx
/Sources/Subs-ReportedContent.php (Line 609)

Type of error: General
Error messageSelect
8: Trying to access array offset on value of type bool

### Steps to reproduce
1. Unknown, in error log
2. 

### Environment (complete as necessary)
- Version/Git revision: 2.1.1
- Database Type:
- Database Version:
- PHP Version: 7.4

### Additional information/references
```
			'msg_id' => $report['id_msg'],
```

### PR DESCRIPTION
**Pull request by jdarwood007**
Fixes #7429

### CODE REVIEW

File: Sources/Actions/Moderation/ReportedContent.php [hunk 1]
```diff
@@ -1215,6 +1215,10 @@ protected function saveModComment(int $report_id, array $data): void
 
 		$report = $this->getReportDetails($report_id);
 
+		if (empty($report)) {
+			return;
+		}
+
```
Comment (Sesquipedalian) [inline Sources/Actions/Moderation/ReportedContent.php]: While we're at it, we should probably move all of this chunk to the top of the function, before we even try to insert the comment. After all, if the report doesn't exist, what are we commenting on?

**Review by Sesquipedalian — CHANGES_REQUESTED** [review]

**Review by Sesquipedalian — APPROVED** [review]
