### PR TITLE
Check on UI side website_title length

### LINKED ISSUE #7532: Database Error: Data too long for column 'website_title' at row 1
#### Description
When a member edits their profile to enter their website title, the input allows more characters than the database column will allow.

### Steps to reproduce
1. Edit a user profile on SMF 2.1.2
2. Enter a very long entry for the website title input 

### Environment (complete as necessary)
- 2.1.2 stable
- mysqlnd
- 8.1.3
- PHP 7.4 & PHP 8.0

### Additional information/references
Can be patched in Subs.php

### PR DESCRIPTION
**Pull request by albertlast**
fixes: #7532

### CODE REVIEW

File: Sources/Profile-Modify.php [hunk 1]
```diff
@@ -642,6 +642,13 @@ function $preload:		A function that is used to load data required for this eleme
 			'size' => 50,
 			'permission' => 'profile_website',
 			'link_with' => 'website',
+			'input_validate' => function(&$value) use ($smcFunc)
+			{
+				if ($smcFunc['strlen']($value) > 250)
```
Comment (Sesquipedalian) [inline Sources/Profile-Modify.php]: This should use `mb_strlen($value)` rather than `$smcFunc['strlen']($value)`. This is because `$smcFunc['strlen']()` counts HTML entities like `&amp;` as single characters, but MySQL will count `&amp;` as five characters.

**Review by Sesquipedalian — CHANGES_REQUESTED** [review]

**Review by Sesquipedalian — APPROVED** [review]
