### PR TITLE
[3.0] Always use canonical path when including files

### LINKED ISSUE #8293: [3.0]: Config quirks
### Basic Information

1.  In Windows, Settings.php is being reloaded constantly, mainly due to it's not being found in a get_included_files() check.  This is due to the different DIRECTORY_SEPARATORs between Windows & linux.
2. eval returns null, which can result in null being assigned to a setting under some circumstances.  E.g., attempting an upgrade, received the following error:

image

### Steps to reproduce

1.  Install 2.1.4
3.  Upgrade to 3.0

### Expected result

A 3.0 forum

### Actual result

WSOD error

### Version/Git revision

4.0 Alpha 2 - current GH

### Database Engine

All

### Database Version

8.4.0

### PHP Version

8.3.8

### Logs

```shell
Fatal error: Uncaught TypeError: Cannot assign null to property SMF\Config::$languagesdir of type string in D:\wamp64\www\84van30\Sources\Config.php:915 Stack trace: #0 D:\wamp64\www\84van30\Sources\Config.php(886): SMF\Config::set(Array) #1 D:\wamp64\www\84van30\upgrade.php(188): SMF\Config::load() #2 {main} thrown in D:\wamp64\www\84van30\Sources\Config.php on line 915
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Sesquipedalian**
On Windows servers, the paths that were used to include files often contained a mix of backslashes and forward slashes, because our code typically uses forward slashes as per Unix/Linux conventions, but saved paths like `Config::$sourcedir` typically used backslashes as per Windows conventions.

This has been known to cause issues in situations where the path of an included file has to be checked for whatever reason. For example, #8293 documents a case where Settings.php is included over and over due to this issue. 

This PR fixes the problem by always using the correct directory separator character in our paths when including files:
- In cases where the path to be included was a hard-coded string, this could be achieved most efficiently by simply replacing literal `/` characters in paths with the `DIRECTORY_SEPARATOR` constant. 7b9a16d implements this.
- In cases where the path to be included was determined programmatically, it was easier to implement a function to canonicalize the path just before including the file. b3be59d implements this.

The new `Config::canonicalpath()` method added in b3be59d is a wrapper for `realpath()` that is also able to handle paths that don't exist.

Fixes #8293.

### CODE REVIEW

**Comment by Sesquipedalian** [comment]
@sbulen, if you can test this, that would be appreciated. In particular, I am looking for confirmation that `Config::canonicalpath()` works as expected on Windows, since I don't have a Windows machine available to test on.

File: Sources/Config.php [hunk 1]
```diff
@@ -2845,6 +2850,129 @@ public static function checkCron(): void
...
+	 *    - If false, relative paths are processed as given.
+	 *    Default: false.
+	 * @param bool $real Whether to get the real path for existing files. This
+	 *    can be set to false if the caller wants to canonicalize a hypothetical
+	 *    path without any possibility of the real file structure interfering
+	 *    with the result.
+	 *    Default: true.
+	 * @return string The canonical file path.
+	 */
+	public static function canonicalpath(string $path, string|bool $base_dir = false, bool $real = true): string
```
Comment (jdarwood007) [inline Sources/Config.php]: Following naming standards, shouldn't this be `canonicalPath`?

File: Sources/Actions/Admin/Logs.php [hunk 2]
```diff
@@ -156,7 +156,7 @@ public function execute(): void
 		];
 
 		if (!empty(self::$subactions[$this->subaction][0])) {
-			require_once Config::$sourcedir . '/' . self::$subactions[$this->subaction][0];
+			require_once Config::canonicalpath(Config::$sourcedir . '/' . self::$subactions[$this->subaction][0]);
```
Comment (jdarwood007) [inline Sources/Actions/Admin/Logs.php]: Just nitpicking a random example.  I'm debating whether it would look better like that or as
```
require_once Config::$sourcedir . DIRECTORY_SEPARATOR . Config::canonicalpath(self::$subactions[$this->subaction][0]);
```
Since we should only need to sanitize the input received from the sub-action itself, knowing that we have already cleaned `$sourcedir`.

Comment (jdarwood007) [reply Sources/Actions/Admin/Logs.php]: Another quick idea is we could do
```
function buildPath(...$args)
{
	return Config::canonicalpath(implode(DIRECTORY_SEPARATOR, $args));
}
```
Then a simple call to it:
```
Config::buildPath([Config::$sourcedir, self::$subactions[$this->subaction][0]));
```

I've seen it in other languages I've worked with where you provide the directory names and it handles the rest.

Comment (Sesquipedalian) [reply Sources/Actions/Admin/Logs.php]: > Just nitpicking a random example. I'm debating whether it would look better like that or as
> 
> ```
> require_once Config::$sourcedir . DIRECTORY_SEPARATOR . Config::canonicalpath(self::$subactions[$this->subaction][0]);
> ```
> 
> Since we should only need to sanitize the input received from the sub-action itself, knowing that we have already cleaned `$sourcedir`.

Not if the relative path in `self::$subactions[$this->subaction][0]` contains directory separators itself.

Comment (Sesquipedalian) [reply Sources/Actions/Admin/Logs.php]: > Another quick idea is we could do
> 
> ```
> function buildPath(...$args)
> {
> 	return Config::canonicalpath(implode(DIRECTORY_SEPARATOR, $args));
> }
> ```
> 
> Then a simple call to it:
> 
> ```
> Config::buildPath([Config::$sourcedir, self::$subactions[$this->subaction][0]));
> ```
> 
> I've seen it in other languages I've worked with where you provide the directory names and it handles the rest.

It's a good idea, sure.

File: Sources/Config.php (hunk 1 above)
Comment (Sesquipedalian) [reply Sources/Config.php]: Meh. We could, I suppose. I modelled that name directly on `realpath()`. If it feels more consistent to you to capitalize the `P`, sure, we can do that.

File: Sources/Actions/Admin/Logs.php (hunk 2 above)
Comment (jdarwood007) [reply Sources/Actions/Admin/Logs.php]: > > Since we should only need to sanitize the input received from the sub-action itself, knowing that we have already cleaned `$sourcedir`.
> 
> Not if the relative path in `self::$subactions[$this->subaction][0]` contains directory separators itself.

It's why I had it wrapped to use the `canonicalpath`, but left the rest.
Not really an issue, just me nitpicking at styling, and wanted to throw it out there if it was liked better.

File: Sources/Config.php (hunk 1 above)
Comment (jdarwood007) [reply Sources/Config.php]: Won't force it, just a comment that we seemed to be using camelCasing for our naming conventions (or at least trying to go that way) and wanted to ensure if it was an oversight, we address it.

**Review by jdarwood007 — APPROVED** [review]
Looks good.  Made some comments about coding styles, which don't impact anything if we decide to not do them.

File: Sources/Actions/Admin/Logs.php (hunk 2 above)
Comment (Sesquipedalian) [reply Sources/Actions/Admin/Logs.php]: Oh, I see. Well, since the same `str_replace()` calls will be made either way, it won't make any performance difference, so it's just a matter of aesthetics. Personally, I find the `/` character is easier to read, so I only manually replaced in with `DIRECTORY_SEPARATOR` where necessary.
