### PR TITLE
fix: Hide unwatched topics from the recent posts pages

### LINKED ISSUE #6907: Unwatched topics still show in the unread topics pages
#### Description
--Description Here--

### Steps to reproduce
1. Have a multi-page tropic
2. Mark only the first page read
3. Set the topic's alert prefs to ignore
4. Observe the topic is still in the unread lists

### Additional information/references
I have a fix coming shortly which  modifies the queries to have the requisite predicate in the `WHERE` clause rather than the `ON` clause of `LEFT JOIN`.

### PR DESCRIPTION
**Pull request by live627**
Move the unwatched predicates from `LEFT JOIN`ed tables to the `WHERE` clause to ensure that the value is picked up as intended. Use `COALESCE` for when the row/value does not exist.

Fix #6907

Signed-off-by: John Rayes <live627@gmail.com>

### CODE REVIEW

File: Sources/Recent.php [hunk 1]
```diff
@@ -930,13 +929,14 @@ function UnreadTopics()
...
-				LEFT JOIN {db_prefix}log_topics AS lt ON (lt.id_topic = t.id_topic AND lt.id_member = {int:current_member} AND lt.unwatched != 1)') . '
+				LEFT JOIN {db_prefix}log_topics AS lt ON (lt.id_topic = t.id_topic AND lt.id_member = {int:current_member})') . '
 				LEFT JOIN {db_prefix}log_mark_read AS lmr ON (lmr.id_board = t.id_board AND lmr.id_member = {int:current_member})
 			WHERE t.' . $query_this_board . ($context['showing_all_topics'] && !empty($earliest_msg) ? '
 				AND t.id_last_msg > {int:earliest_msg}' : (!$context['showing_all_topics'] && empty($_SESSION['first_login']) ? '
 				AND t.id_last_msg > {int:id_msg_last_visit}' : '')) . '
 				AND COALESCE(lt.id_msg, lmr.id_msg, 0) < t.id_last_msg' . ($modSettings['postmod_active'] ? '
-				AND t.approved = {int:is_approved}' : '') . '',
+				AND t.approved = {int:is_approved}' : '') . '
+				AND COALESCE(lt.unwatched, 0) != 1',
```
Comment (albertlast) [inline Sources/Recent.php:939]: is COALESCE realy needed here?
it harm the performance of the query here.

Comment (live627) [reply Sources/Recent.php:939]: Yes,      for the reason outlined in the op/commit message.

**Review by Sesquipedalian — APPROVED** [review]
