### PR TITLE
Fixes various issues with DbPackages functions

### LINKED ISSUE #7417: pacman & pg: indexes not removed when mods uninstalled
#### Description
If you install a mod on a pg forum that creates indexes on existing tables, all is OK.  But when you uninstall that mod, the indexes remain.  

Columns and tables are removed properly, but indexes are not.  

### Steps to reproduce
1. Create a pg forum
2. Install a mod that creates indexes on existing tables
3. Uninstall the mod; the indexes remain

### Environment (complete as necessary)
- Version/Git revision: Current
- Database Type: pg
- Database Version: 14
- PHP Version: 8.0.13

### Additional information/references

### LINKED ISSUE #7418: smf_db_list_columns defaults and nulls
I've been working more with SMF's smf_db_list_columns and smf_db_change_column functions and have come to the conclusion we don't have it working right yet for defaults.  I'm starting this to allow a discussion and present the bug.

To start, PHP has a horrible handling for NULLs.  take for example this:
```
<?php
$a = null;

var_dump(isset($a));
var_dump(is_null($a));
var_dump(isset($b));
var_dump(is_null($b));
```

PHP will report $a is not set but is null.  However for $b, PHP will report $b is not set, but throw a variable undefined error on is_null, then return true.  This is documented in PHP's manual,  but I find it a very horrible syntax that is_null will throw a variable undefined error.   If the variable your checking is in an array, you can use array_key_exists as this works as expected.

Now onto MySQL at least.  The default column has some oddities that require checking the null column.
1. If default is "NULL" and the nullable column is set to "NOT NULL", then the field is required to have a value in it and can not contain null.  In PMA this shows up as "NONE"
2. If the default is "NULL" and the nullable column is "NULL", then the column can contain nulls.
3. The value can either be a int or a string as well.  Thanks to PHP's loose type handling, this is only a problem if you want to do a strict type check.  But it makes it more difficult for us to do checks against because if we do strict type checks, it can fail between the '0' === 0.

This creates issues when you are checking and comparing columns.  I don't think SMF's code is up to snuff on getting this all right.  I've wrote some code, but I dislike the changes.  This is the sample of the changes for list_columns
```
				$default = null;
				// Column is nullalbe and the default is NULL.
				if (is_null($row['Default']) && $row['Null'] == 'YES')
					$default = null;
				// Column is not nullable and the default is set to null, meaning no default.
				elseif (is_null($row['Default']) && $row['Null'] == 'NO')
					$default = false;
				elseif (isset($row['Default']) && $row['Default'] == '\'\'')
					$default = '';
				elseif (isset($row['Default']))
					$default = stripslashes($row['Default']);
```

However the code changes for change_columns is:
```
		if (!array_key_exists('default', $column_info))
			$default = $old_info['default'];
		elseif ($old_info['default'] === false)
			$column_info['default'] = null;

[...]

		// Fix the default.
		$default = '';
		if (is_null($column_info['default']) && empty($column_info['not_null']))
			$default = 'NULL';
		elseif (isset($column_info['default']))
			$default = '\'' . $smcFunc['db_escape_string']($column_info['default'], self::$db_connection) . '\'';
```

It is fairly ugly, but it does the work.  Anyone else have a better opinion on trying to get this right?

### LINKED ISSUE #7419: pacman, pg & mysql: TEXT + indexes
#### Description

If a mod needs a TEXT field with an index...  Mysql forces you to specify an index length to create a partial index.  But pg chokes when an index length is specified in pacman.  

I may be missing something...  But, it appears to me that, ATM, it's impossible for a MOD to create a TEXT field with an index that will install on both pg and mysql.  

Possible fix:  Note that where we have partial indexes on text fields in SMF today, the installer & upgrader treat them differently in pg vs mysql.  PG never specifies the length.  It may be sufficient for pacman to drop the length in pg, just like it does in the installer/upgrader.

### Environment (complete as necessary)
- Version/Git revision:  Current
- Database Type: pg & mysql

### Additional information/references
Note that VARCHAR(1024), + a full index works for mysql 8 & pg.  
But...  
Mysql 5.6 wouldn't let you do that due to (the index's) index length.  (This restriction was addressed in mysql 5.7.)  In fact, mysql 5.6 doesn't let you do VARCHAR(512) either.

VARCHAR(255) + a full index is the only approach that appears to work across mysql 5.6, mysql 8, & pg where you need a text column with an index today.

**_NOTE that if submitting a PR, we will want to see proof of testing on pg & mysql.  Before & after screenshots._**

### LINKED ISSUE #7420: pacman: Legacy NULL setting doesn't work
#### Description
When the NOT_NULL setting was added to pacman, the prior NULL setting was kept around for legacy support.

It doesn't appear to be working.  We should either make it work or remove it.

### Environment (complete as necessary)
- Version/Git revision: Current
- Database Type: mysql (didn't check pg)

### Additional information/references
**_NOTE that if submitting a PR, we will want to see proof of testing on pg & mysql. Before & after screenshots._**

### PR DESCRIPTION
**Pull request by jdarwood007**
1. We sometimes will pass in `databasename`.`table_name` and have not uses a select database.  So we try to parse our the database info when running select commands that need this such as list tables, list keys, list columns.
2. When working with default, we need to handle nulls properly as a default using the literal NULL.  We should also try to handle numericals better
3. MySQL doesn't allow you to do an index on a text column without a length.  Force one if found.
4. Postgresql doesn't support a length on an index, so strip it out if specified.
5. Postgresql didn't handle indexes well in all scenarios because they are prefixed with the table name and we may not pass the index name prefixed with the table name.
6. Postgresql didn't do NULLs properly because we didn't check the right value returned from the list of columns.
7. Avoid overwriting $table_name, as this can cause unexpected results when the parsed name is sent to other functions.
8. MySQL with text index needs a limit, so we try to add one.

Attached are simple scripts I used to test these.  Please modify the scripts and send them back if you are finding cases where we are still not doing something right.

[test-7417.php.txt](https://github.com/SimpleMachines/SMF2.1/files/8456163/test-7417.php.txt)
[test-7420.php.txt](https://github.com/SimpleMachines/SMF2.1/files/8456164/test-7420.php.txt)
[test-7419.php.txt](https://github.com/SimpleMachines/SMF2.1/files/8456165/test-7419.php.txt)
[test-7418.php.txt](https://github.com/SimpleMachines/SMF2.1/files/8456166/test-7418.php.txt)

Fixes #7417 
Fixes #7418 
Fixes #7419 
Fixes #7420 

I'm doing this as a WIP right now and asking @albertlast and @sbulen to provide feedback.  But once we are happy there, this will want more dev eyes on it.  Its a lot of changes to make.

### CODE REVIEW

**Comment by jdarwood007** [comment]
FYI,
MySQL 8.0 on Ubuntu
PostgreSQL: PostgreSQL 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit

File: Sources/DbPackages-postgresql.php [hunk 1]
```diff
@@ -150,28 +151,28 @@ function smf_db_create_table($table_name, $columns, $indexes = array(), $paramet
...
+					DROP SEQUENCE IF EXISTS ' . $short_table_name . '_seq',
 					array(
 						'security_override' => true,
 					)
 				);
 
 			if (!$old_table_exists)
 				$smcFunc['db_query']('', '
-					CREATE SEQUENCE ' . $table_name . '_seq',
+					CREATE SEQUENCE ' . $short_table_name . '_seq',
```
Comment (albertlast) [inline Sources/DbPackages-postgresql.php:172]: i still would like to see that sequence with owned get created here,
like done in this pr: https://github.com/SimpleMachines/SMF2.1/pull/6323

**Comment by albertlast** [comment]
It's always confusing that the word database is used everywhere,
but not meant to be.
by simple reason mysql didn't support database and you can't "change" database in the way like here done in the code use in pg.

File: Sources/DbPackages-postgresql.php [hunk 2]
```diff
@@ -104,27 +104,28 @@ function db_packages_init()
...
 	$old_table_exists = false;
 
 	// Strip out the table name, we might not need it in some cases
 	$real_prefix = preg_match('~^("?)(.+?)\\1\\.(.*?)$~', $db_prefix, $match) === 1 ? $match[3] : $db_prefix;
+	$database = !empty($match[2]) ? $match[2] : $db_name;
 
 	// With or without the database name, the fullname looks like this.
 	$full_table_name = str_replace('{db_prefix}', $real_prefix, $table_name);
-	$table_name = str_replace('{db_prefix}', $db_prefix, $table_name);
+	$short_table_name = str_replace('{db_prefix}', $db_prefix, $table_name);
```
Comment (albertlast) [inline Sources/DbPackages-postgresql.php:118]: why is ths not real_table_name like in mysql?

File: Sources/DbPackages-postgresql.php [hunk 3]
```diff
@@ -581,21 +588,21 @@ function smf_db_change_column($table_name, $old_column, $column_info)
...
-				DROP SEQUENCE IF EXISTS ' . $table_name . '_seq',
+				DROP SEQUENCE IF EXISTS ' . $short_table_name . '_seq',
 				array(
 					'security_override' => true,
 				)
 			);
 
 			$smcFunc['db_query']('', '
-				CREATE SEQUENCE ' . $table_name . '_seq',
+				CREATE SEQUENCE ' . $short_table_name . '_seq',
```
Comment (albertlast) [inline Sources/DbPackages-postgresql.php:607]: like to owned like mention before

**Comment by albertlast** [comment]
run the test script, checked the the log file of pg in data directory and found no error messages,
so test run clean throw pg.

File: Sources/DbPackages-postgresql.php (hunk 1 above)
Comment (jdarwood007) [reply Sources/DbPackages-postgresql.php:172]: Since that PR wasn't merged.  I don't think this PR should address it.  Even if it is right.

**Comment by jdarwood007** [comment]
> It's always confusing that the word database is used everywhere, but not meant to be. by simple reason mysql didn't support database and you can't "change" database in the way like here done in the code use in pg.

Any suggestions?

**Comment by jdarwood007** [comment]
For your other question on real_table_name.  The first fixes I worked on changed everything to use short_table_name because modifying $table_name was sometimes causing issues when it got passed into other functions.  This was typically with mysql, but I pushed it into the postgresql to be consistent.  The second issue then I found was that in MySQL, when running in SSI, we do not issue a select database command, but run with `database`.`table_name` on all commands.  This caused issue where we expected things like getting a list of tables in a database, but we never selected a database, so the code would use the database configured in SMF.  Which worked until you issued a command in another database.  So for some functions, I have to parse out any possible database match and try to use that, so we issue the commands to the correct database.  So since not all functions needed this fix, I didn't have to do it to all.  But some things like mysql still needed more of a helping hand to get the job done right.

We ignore the schema in postgresql, so at least we don't have to deal with that.

File: Sources/DbPackages-postgresql.php (hunk 1 above)
Comment (sbulen) [reply Sources/DbPackages-postgresql.php:172]: I agree with @albertlast that an OWNED BY would be appropriate here.

In pg, sequences are standalone things, and must be associated with a column explicitly.  Not like in mysql with AUTO INCREMENT.  In mysql, if you delete the table, the auto increment goes away.  This doesn't happen in pg in SMF today, because we created all the sequences without specifying owners.

So what's the problem???   Assume you installed a pg-based SMF forum, & you need to start over.  So, you delete all the tables and attempt to reinstall.  That produces many errors today, because - among other things - you get duplicates on all the sequences.  Making the columns the owners of the sequences ensures they get deleted when the tables are deleted.  

**_Admittedly - not a major or high priority issue..._**  But the only error-free way to reinstall a pg smf forum today is to drop & recreate the pg db.  Deleting the tables isn't enough.

(Tangent alert:  And once you get past the sequence errors, you may encounter duplicate FUNCTION errors...)

The problem with that other PR is that the approach is highly unusual - it alters the pg database directly.  The equivalent would be to add a table to mysql, but not with a CREATE TABLE command, but by adding rows in the TABLE and COLUMNS tables in mysql's information_schema...  What that PR should really do is simply add the OWNED BYs to the install/upgrade scripts.

**Comment by albertlast** [comment]
> > It's always confusing that the word database is used everywhere, but not meant to be. by simple reason mysql didn't support database and you can't "change" database in the way like here done in the code use in pg.
> 
> Any suggestions?

called schema, since it is that: https://dev.mysql.com/doc/refman/8.0/en/glossary.html#glos_schema

File: Sources/DbPackages-postgresql.php (hunk 1 above)
Comment (jdarwood007) [reply Sources/DbPackages-postgresql.php:172]: Is it acceptable to say then we should make that PR a prereq for adding it into this PR?  We don't support it today and that PR adds it.  But we don't want to half ask it in this PR with that.

**Comment by jdarwood007** [comment]
In pg we use the public schema.  So wouldn't this get confusing?  Its MySQL in reality that is wrong here.  They should be using a schema on the database.  Which then would align it with most others.

**Comment by albertlast** [comment]
in pg we didn't support schema, for reason i doesn't understand,
so smf get installed/working in the default schema,
which deppends on the database user how is used(common is public).

But the point is still,
that the <schema>.<table> and to call the first part database is wrong.

**Comment by sbulen** [comment]
I have confirmed this fixes #7417 via testing on pg & mysql.

**Comment by sbulen** [comment]
I was testing #7419 but it fails spectacularly on pg...

The package-info.xml of the failed pg test looked like:
```
<?php

global $smcFunc;

if (!isset($smcFunc['db_create_table']))
	db_extend('packages');

$create_tables = array(
	'a_test_record' => array(
		'columns' => array(
		    array(
			   'name' => 'id_atest',
				'type' => 'INT',
				'not_null' => true,
			),
		    array(
			   'name' => 'fails_in_pg',
				'type' => 'TEXT',
				'not_null' => true,
			),
			array(
				'name' => 'fails_in_mysql_56',
				'type' => 'varchar',
				'size' => 512,
				'default' => '',
				'not_null' => true,
			),
		),
		'indexes' => array(
			array(
				'type' => 'primary',
				'columns' => array('id_atest'),
			),
			array(
				'type' => 'index',
				'name' => 'ix_test_text',
				'columns' => array('fails_in_pg (64)'),
			),
			array(
				'type' => 'index',
				'name' => 'ix_test_ix_length',
				'columns' => array('fails_in_mysql_56'),
			),
		),
	),
);

foreach ($create_tables AS $table_name => $data)
	$smcFunc['db_create_table']('{db_prefix}' . $table_name, $data['columns'], $data['indexes']);

```

Mysql works OK.  The attempt to install the same mod in pg looks like:
image

**Comment by sbulen** [comment]
I was testing #7420 , but it appears to fail on both mysql & pg.

To test, I added two columns, one with NULL = true, and one with NULL = false.

The results were such that both were nullable, i.e., the setting didn't have any effect.  This was true in both pg and mysql.

If this particular NULL setting is a legacy setting, i.e., a 2.0 setting, maybe we should just **_remove it entirely._**  That would be a satisfactory result, IMO.  The new setting, the NOT_NULL setting, seems to work fine.  Given that 2.0 mods don't work in 2.1, I'm not sure that we need to migrate support for the older NULL version???

The package-info.xml file looked like:
```
<?php

global $smcFunc;

if (!isset($smcFunc['db_create_table']))
	db_extend('packages');

$create_tables = array(
	'another_test_record' => array(
		'columns' => array(
		    array(
			   'name' => 'id_atest2',
				'type' => 'INT',
				'not_null' => true,
			),
		    array(
				'name' => 'null_false',
				'type' => 'varchar',
				'size' => 50,
				'default' => '',
				'NULL' => false,
			),
			array(
				'name' => 'null_true',
				'type' => 'varchar',
				'size' => 50,
				'default' => '',
				'NULL' => true,
			),
		),
		'indexes' => array(
			array(
				'type' => 'primary',
				'columns' => array('id_atest2'),
			),
		),
	),
);

foreach ($create_tables AS $table_name => $data)
	$smcFunc['db_create_table']('{db_prefix}' . $table_name, $data['columns'], $data['indexes']);
```

The results in mysql indicated both were nullable, i.e., the NULL setting had no effect:
image

The results in pg indicated both were nullable, i.e., the NULL setting had no effect:
image

**Review by sbulen — CHANGES_REQUESTED** [review]
The fixes for 7419 & 7420 both appeared to have failed.  See comments.

**Comment by jdarwood007** [comment]
I will get some more testing in.
I think we will need to accept
```
'default' => null,
'default' => '',
'default' => 0,
'default' => false
```

With false being the default..

**Comment by sbulen** [comment]
> With false being the default..

Since mysql uses an implicit default of '' for text/character columns, I think we need to use that for consistency across pg & mysql...

I think the pg command, when no default is specified in the config to pacman, needs to look something like:
`ALTER TABLE xxxxx NOT NULL default ''; DROP DEFAULT;`

This will mimic mysql's implicit default behavior for text/char, and will work for rows with existing records (#7421 ).  

I have not experimented with ints, etc....

**Comment by jdarwood007** [comment]
if we use false for the default, it shouldn't send any default.  The field would require something then, Unless the nullable is set which would allow it to be null?

**Comment by albertlast** [comment]
> I was testing #7419 but it fails spectacularly on pg...
> 
> The package-info.xml of the failed pg test looked like:
> 
> ```
> <?php
> 
> global $smcFunc;
> 
> if (!isset($smcFunc['db_create_table']))
> 	db_extend('packages');
> 
> $create_tables = array(
> 	'a_test_record' => array(
> 		'columns' => array(
> 		    array(
> 			   'name' => 'id_atest',
> 				'type' => 'INT',
> 				'not_null' => true,
> 			),
> 		    array(
> 			   'name' => 'fails_in_pg',
> 				'type' => 'TEXT',
> 				'not_null' => true,
> 			),
> 			array(
> 				'name' => 'fails_in_mysql_56',
> 				'type' => 'varchar',
> 				'size' => 512,
> 				'default' => '',
> 				'not_null' => true,
> 			),
> 		),
> 		'indexes' => array(
> 			array(
> 				'type' => 'primary',
> 				'columns' => array('id_atest'),
> 			),
> 			array(
> 				'type' => 'index',
> 				'name' => 'ix_test_text',
> 				'columns' => array('fails_in_pg (64)'),
> 			),
> 			array(
> 				'type' => 'index',
> 				'name' => 'ix_test_ix_length',
> 				'columns' => array('fails_in_mysql_56'),
> 			),
> 		),
> 	),
> );
> 
> foreach ($create_tables AS $table_name => $data)
> 	$smcFunc['db_create_table']('{db_prefix}' . $table_name, $data['columns'], $data['indexes']);
> ```
> 
> Mysql works OK. The attempt to install the same mod in pg looks like: image

Maybe the paste of pg log from data directory would be also helpfull.

**Comment by jdarwood007** [comment]
[test-7419b.php.txt](https://github.com/SimpleMachines/SMF2.1/files/8500740/test-7419b.php.txt)

Here is the 7419b to test against @sbulen script.  Looks like we duplicate work in the create table function.  In a future version of SMF, we should move this work to a sub function that then the create tabla and create index functions can both use to generate the correct logic.

I fixed the issue with the transaction.  We have to abort the transaction to log the error.  As it is a fatal error, it should not continue and abort execution anyways.  The error was occurring because it was trying to insert into the error log and couldn't because we are in the transaction that failed.

**Comment by jdarwood007** [comment]
[test-7420b.php.txt](https://github.com/SimpleMachines/SMF2.1/files/8500754/test-7420b.php.txt)

@sbulen Looks like your 7420 script was failing because the key was upper case and the code was looking for lower case.  I just ran it against array_change_key_case which lowercases the key, so we can find it.  Once that was done, it works.

**Review by albertlast — COMMENTED** [review]
I'm not sure,
if mysql allow the same logic.

Possible that every ddl is an own transaction.

**Comment by jdarwood007** [comment]
We are doing a transaction in pg because we have to issue a create table statement and then the create indexes statement.  If any of those fail, the entire create table should fail.  In MySQL we can do it all in one statement.

**Comment by jdarwood007** [comment]
When we have a auto column (/sequence for pg) we should
1. Enforce that it is not null
2. Ensure it does not have a default (as the auto/sequence will populate it).

I think this is fine restriction to enforce here and ensures all the database systems are happy.

**Review by sbulen — APPROVED** [review]
I retested, and #7417 #7419 and #7420 all work now.   

Good stuff...

#7419 still fails on MySQL 5.6, but not sure what we can do about that.

**Comment by jdarwood007** [comment]
Whats your feeling regarding the auto column issue mentioned above?  I think that should be resolved here to round up all the issues we have.

**Comment by sbulen** [comment]
I don't think I've seen a problem with sequences or auto-increments...  

I'm not sure what problem we're trying to solve...

**Comment by jdarwood007** [comment]
I didn't make a test script, but I tested creating a table with a id column that was auto, default of 0 and null.  It failed.  Because well you can't have that.  If you need a test script, I can create one.

**Comment by sbulen** [comment]
I just did a before & after, both mysql & pg.  The column was auto-incremented, default 0, & NULL was true, e.g., it was nullable.

I had no issues with or without this PR.  It always installed clean with no errors, and the column was auto incremented (w/sequence in pg).

It's true that the default & nullable were ignored.  But I saw the same behavior before & after.

I wonder if reverting the prior null-behavior commit changed the behavior.

**Comment by jdarwood007** [comment]
I can't reproduce it anymore.  So at this time, this is ready for approvals.

**Comment by sbulen** [comment]
I just tested the "191" logic, by attempting to create the large index in mysql 5.6, and got the following.  
image

**Comment by jdarwood007** [comment]
Did I do something wrong then?  The 191 is enforced, unless you specify a index length

```
	// MySQL If its a text column, we need to add a size.
	$cols = $smcFunc['db_list_columns']($table_name, true);
	foreach ($index_info['columns'] as &$c)
	{
		$c = trim($c);

		// If a size was already specified, we won't be able to match it anyways.
		if (!isset($cols[$c]) || !in_array($cols[$c]['type'], array('text', 'mediumntext', 'largetext', 'varchar', 'char')))
			continue;

		$c .= '(191)';
	}
```

**Comment by sbulen** [comment]
I suspect the issue was the $default issue?

It is also saying there are conflicts now.  

I'll retest after the conflicts are resolved.

**Comment by jdarwood007** [comment]
I'm not seeing conflicts

**Comment by sbulen** [comment]
Maybe it only applies to rebases?

I'll retest to see if the default fix changed anything.

Screenshot_20220427-180726_Firefox

**Comment by jdarwood007** [comment]
Screen Shot 2022-04-27 at 6 21 29 PM

I did merge release-2.1 to sync the revert of the patch.

**Comment by jdarwood007** [comment]
Your right.. it won't rebase and merge..  but can do a merge request or squash.

**Comment by sbulen** [comment]
That's a merge, not a rebase.  I think the way you merged some commits mid-stream prevents a rebase going forward.  That's all that message means, I think.  You will see it, I think, if you change from merge to rebase.

**Comment by jdarwood007** [comment]
Well I can try to fix it or we just let it do a merge/squash.  I've always used the merge.

**Comment by sbulen** [comment]
OK I retested the 191 fix, and I am still having index length issues in mysql 5.6.   

The $default errors are gone, so they were not related.

It looks like it is not actually using the 191, AFAICT.  (bug_test_2.zip works on mysql 8, but not on mysql 5.6.)

bug_test_2:
```
<?php

global $smcFunc;

if (!isset($smcFunc['db_create_table']))
	db_extend('packages');

$create_tables = array(
	'a_test_record' => array(
		'columns' => array(
		    array(
			   'name' => 'id_atest',
				'type' => 'INT',
				'not_null' => true,
			),
		    array(
			   'name' => 'fails_in_pg',
				'type' => 'TEXT',
				'not_null' => true,
			),
			array(
				'name' => 'fails_in_mysql_56',
				'type' => 'varchar',
				'size' => 512,
				'default' => '',
				'not_null' => true,
			),
		),
		'indexes' => array(
			array(
				'type' => 'primary',
				'columns' => array('id_atest'),
			),
			array(
				'type' => 'index',
				'name' => 'ix_test_text',
				'columns' => array('fails_in_pg (64)'),
			),
			array(
				'type' => 'index',
				'name' => 'ix_test_ix_length',
				'columns' => array('fails_in_mysql_56'),
			),
		),
	),
);

foreach ($create_tables AS $table_name => $data)
	$smcFunc['db_create_table']('{db_prefix}' . $table_name, $data['columns'], $data['indexes']);

```

**Comment by sbulen** [comment]
Backtrace:
image

**Comment by sbulen** [comment]
Note:  To emulate a prefix length of 767 in current mysql, you use innodb tables & change innodb_default_row_format to 'compact', which was the default prior to mysql 5.7.

**Comment by sbulen** [comment]
> Well I can try to fix it or we just let it do a merge/squash. I've always used the merge.

Nope, leave it be.  Sorry for the tangent.

**Comment by jdarwood007** [comment]
Sent up a change that should fix it.  But if not, I will need to get a 5.6 test env setup.

**Comment by sbulen** [comment]
Woohoo!  That worked.  This is from my 5.6 environment:
image

What I think I'll do some time over the next couple of days is repeat all the tests again, just to be safe.

**Comment by sbulen** [comment]
Putting this out here:  With these fixes we are going to support pg far, far better than we have in the past.  Many more mods are going to be able to install & work...

File: Sources/Subs-Db-postgresql.php [hunk 4]
```diff
@@ -913,6 +922,10 @@ function smf_db_error_insert($error_array)
 	if (filter_var($error_array[2], FILTER_VALIDATE_IP) === false)
 		$error_array[2] = null;
 
+	// If we are in a transaction, abort.
+	if ($inTransaction)
+		$smcFunc['db_transaction']('rollback');
```
Comment (albertlast) [inline Sources/Subs-Db-postgresql.php]: we are here in an error case,
don't expect anything and test everything before use.

File: Sources/DbPackages-postgresql.php (hunk 1 above)
Comment (albertlast) [reply Sources/DbPackages-postgresql.php:172]: you don't need to add the pr,
you should only add the logic to the code here.

File: Sources/Subs-Db-postgresql.php (hunk 4 above)
Comment (jdarwood007) [reply Sources/Subs-Db-postgresql.php]: I'm not sure what your saying here.  Can you clarify that?

I assume your saying something about being in an error state and we are not testing better?  If you have an idea for a better error test let me know.  I simply global the $inTransaction, and set it to true when we start the transaction and false after we commit.  So if a error occurs while inside the transaction, we issue the rollback.

File: Sources/DbPackages-postgresql.php (hunk 1 above)
Comment (jdarwood007) [reply Sources/DbPackages-postgresql.php:172]: My logic here is your PR adds the owned by for the sequences.  My PR does not touch on this at all as it addresses issues with logic inconsistencies between MySQL and PostgreSQL.    If your PR merges, then I agree with your statement and my PR should be required to have the logic for the sequence owner.  But since it isn't, I don't feel my PR should address this.

If you don't agree with this, you can ping Sesq regarding this as an individual who isn't involved in this PR yet and as the Lead Dev would be the final decision maker regarding this.

File: Sources/Subs-Db-postgresql.php (hunk 4 above)
Comment (albertlast) [reply Sources/Subs-Db-postgresql.php]: the reason is clear and fine,
but you use the variables without testing.
smf use empty() for the most cases,
so i would expect to do this in this way here too.

Comment (jdarwood007) [reply Sources/Subs-Db-postgresql.php]: That makes sense.  Updated

Comment (albertlast) [reply Sources/Subs-Db-postgresql.php]: dunno if it make sense, but could we also test $smcFunc['db_transaction']('rollback'); if it exists?

Comment (jdarwood007) [reply Sources/Subs-Db-postgresql.php]: Why would it not exists?  Its defined in the Subs file.  If it doesn't exist, nothing is working.

Comment (albertlast) [reply Sources/Subs-Db-postgresql.php]: since we are here in the error part so we can't assume that anything is right from here,
reason why we also use prepared statement since it only safe way to hanlde most cases.

**Comment by Sesquipedalian** [comment]
Is this ready to merge?

File: Sources/Subs-Db-postgresql.php (hunk 4 above)
Comment (jdarwood007) [reply Sources/Subs-Db-postgresql.php]: @Sesquipedalian Do you want me to add a existence check here as albertlast has suggested

Comment (Sesquipedalian) [reply Sources/Subs-Db-postgresql.php]: It's hard to imagine a scenario where this code could be executed before `$smcFunc['db_transaction']()` became defined. 

Even so, I'd suggest that you simply call `smf_db_transaction()` directly rather than via `$smcFunc['db_transaction']()`.

File: Sources/DbPackages-mysql.php [hunk 5]
```diff
@@ -420,13 +444,22 @@ function smf_db_change_column($table_name, $old_column, $column_info)
...
+
 	if ($size !== null)
 		$type = $type . '(' . $size . ')';
 
 	$smcFunc['db_query']('', '
-		ALTER TABLE ' . $table_name . '
+		ALTER TABLE ' . $short_table_name . '
 		CHANGE COLUMN `' . $old_column . '` `' . $column_info['name'] . '` ' . $type . ' ' . (!empty($unsigned) ? $unsigned : '') . (!empty($column_info['not_null']) ? 'NOT NULL' : '') . ' ' .
-			(!isset($column_info['default']) ? '' : 'default \'' . $smcFunc['db_escape_string']($column_info['default']) . '\'') . ' ' .
+				($default === '' ? '' : 'DEFAULT ' . $default) . ' ' .
```
Comment (Sesquipedalian) [inline Sources/DbPackages-mysql.php]: Nit: unnecessary extra leading white space
