### PR TITLE
Fixes #3247

### LINKED ISSUE #3247: Too many login attempts gives A LOT of errors due menu and other template related code.
I have been seeing errors in my error log about non existing indexes and such.

```
2: array_intersect(): Argument #2 is not an array
8: Undefined index: permissions
```

 I obtained the following stacktrace:

```
/forum/Sources/Security.php:918    array_intersect
/forum/Sources/Subs.php:3861    allowedTo
/forum/Sources/Subs.php:2978    setupMenuContext
/forum/Sources/Subs.php:3101    setupThemeContext
/forum/Sources/Subs.php:2757    template_header
/forum/Sources/Errors.php:399    obExit
/forum/Sources/Errors.php:199    setup_fatal_error_context
/forum/Sources/LogInOut.php:856    fatal_lang_error
/forum/Sources/Load.php:446    validatePasswordFlood
/forum/index.php:144    loadUserSettings
/forum/index.php:118    smf_main
```

It seems that the user's permissions are not loaded (Since they do not get logged in) but somehow it is expected to exist later on.
In addition no ip adress information is logged for these errors.

Edit, using a MySQL query, based on the fact that the ip logging fails I obtained several more related errors and messages.

``` SQL
select count(*),url,message,stack from smf_log_errors smp WHERE smp.ip = '' GROUP BY message,stack;
```

It seems there are a total of 66 different error messages associated with this.

### PR DESCRIPTION
**Pull request by sbulen**
loadTheme() can, in certain circumstances, get called very early in the logon process, e.g., via fatal_lang_error() via validatePasswordFlood() via loadUserSettings().  In these instances, $user_info is not set, and this triggers 80+ error messages, e.g., undefined index, etc.  ($user_info is set later in loadUserSettings(), after the call to validatePasswordFlood()...)

loadTheme() already attempts to deal with missing $user_info, but it does so by filling in blanks in $context['user'].  This PR loads 'guest' values in $user_info as well.  

Feedback welcome.  I considered a rewrite of loadUserSettings() to call validatePasswordFlood() later in the process, but I wasn't sure this is the ONLY scenario when loadTheme() or fatal_lang_error() would get called so early.

### CODE REVIEW

File: Sources/Load.php [hunk 1]
```diff
@@ -1942,6 +1943,21 @@ function loadTheme($id_theme = 0, $initialize = true)
...
+		$user_info['username'] = $txt['guest_title'];
+		$user_info['language'] = $language;
+		$user_info['email'] = '';
+		$user_info['smiley_set'] = '';
+		$user_info['permissions'] = array();
+		$user_info['groups'] = array();
+		$user_info['ignoreusers'] = array();
+		$user_info['possibly_robot'] = true;
+		$user_info['time_offset'] = 0;
+		$user_info['time_format'] = $modSettings['time_format'];
```
Comment (Oldiesmann) [inline Sources/Load.php]: Can't we just define all of these in a single array() statement like we do with `$context['user']` above?

Comment (sbulen) [reply Sources/Load.php]: Yes, I'll need a day or two to change & retest....

**Comment by sbulen** [comment]
Requested changes made.

**Review by frandominguezl — APPROVED** [review]
