### PR TITLE
Fix undefined sa issue

### LINKED ISSUE #7640: Accessing The Ban List Produces Undefined Array Key "sa"
#### Description
Get 4 errors in error log when trying to access the ban list.

### Steps to reproduce
1.  Fresh Install of 2.1.3
2.  Access the Ban List from the "Administration Center"  This only happens when using the icon on the "Administration Center" page.
3.  Check error log after and see 4 errors. 2: Undefined array key "sa"

### Environment (complete as necessary)
- Version/Git revision: SMF 2.1.3
- Database Type: MariaDB
- Database Version: 8.0.23
- PHP Version: 8.0.23

### Additional information/references
#0: smf_error_handler()
    Called from [C:\xampp8.0\htdocs\smf\Sources\ManageBans.php on line 72](https://127.0.0.1/smf/index.php?action=admin;area=logs;sa=errorlog;file=QzpceGFtcHA4LjBcaHRkb2NzXHNtZlxTb3VyY2VzXE1hbmFnZUJhbnMucGhw;line=72)
    #1: Ban()
    Called from [C:\xampp8.0\htdocs\smf\Sources\Admin.php on line 499](https://127.0.0.1/smf/index.php?action=admin;area=logs;sa=errorlog;file=QzpceGFtcHA4LjBcaHRkb2NzXHNtZlxTb3VyY2VzXEFkbWluLnBocA==;line=499)
    #2: AdminMain()
    Called from [C:\xampp8.0\htdocs\smf\index.php on line 191](https://127.0.0.1/smf/index.php?action=admin;area=logs;sa=errorlog;file=QzpceGFtcHA4LjBcaHRkb2NzXHNtZlxpbmRleC5waHA=;line=191)

### PR DESCRIPTION
**Pull request by sbulen**
Fixes #7640 
Replaces #7605 

Uses alternate approach suggested in #7605 .  This allows the hook to redefine the menu if needed, & still addresses the error.

### CODE REVIEW

File: Sources/ManageBans.php [hunk 1]
```diff
@@ -80,6 +76,10 @@ function Ban()
 	// Default the sub-action to 'view ban list'.
 	$_REQUEST['sa'] = isset($_REQUEST['sa']) && isset($subActions[$_REQUEST['sa']]) ? $_REQUEST['sa'] : 'list';
 
+	// Mark the appropriate menu entry as selected
+	if (array_key_exists($_REQUEST['sa'], $context[$context['admin_menu_name']]['tab_data']['tabs']))
```
Comment (Sesquipedalian) [inline Sources/ManageBans.php:80]:
```suggestion
	if (isset($_REQUEST['sa']) && array_key_exists($_REQUEST['sa'], $context[$context['admin_menu_name']]['tab_data']['tabs']))
```

**Review by Sesquipedalian — CHANGES_REQUESTED** [review]

File: Sources/ManageBans.php (hunk 1 above)
Comment (Sesquipedalian) [reply Sources/ManageBans.php:80]: Derp. Never mind.

**Review by Sesquipedalian — APPROVED** [review]

**Review by jdarwood007 — APPROVED** [review]
Works for me.
