### PR TITLE
Uses built-in 'matcher' callback of At.js

### LINKED ISSUE #7687: Inserting mentions in WYSIWYG mode can mess with cursor position
#### Description
Inserting mentions in WYSIWYG mode messes with the cursor position when trying to edit the same paragraph that the mention appears in. Specifically, under certain conditions (see below) the cursor will keep jumping to the end of the paragraph when trying to edit a paragraph that contains a mention.

### Steps to reproduce
1. Put the following text into the quick reply (replace "@test1" with a username on your test forum):
```
Lorem ipsum dolor sit amet, consectetuer adipiscing elit. @test1  Aenean tempus justo sed arcu. Sed ut neque. Nam quis odio in nulla dapibus laoreet. Suspendisse interdum volutpat ligula. 

Nullam sagittis nunc quis massa. @test1 Curabitur a pede vel risus mollis dignissim. Aenean nec massa. Vivamus at tellus. Sed ac nunc. Pellentesque feugiat ultricies quam. Ut porta turpis commodo pede dignissim laoreet.
```
2. Click the preview button to go to the full post authoring form.
3. Click somewhere after the mention in the second paragraph.
4. Observe how the cursor jumps to the end of the paragraph.

### Environment (complete as necessary)
- Version/Git revision: 5bc137d
- Database Type: N/A
- Database Version: N/A
- PHP Version: N/A

### Additional information/references
Original report: https://www.simplemachines.org/community/index.php?topic=585125.0

### PR DESCRIPTION
**Pull request by Sesquipedalian**
Fixes #7687

For those who are curious, the issue was that the custom 'matcher' callback we were using would capture everything from the `@` to the end of the line, rather than just the actual matching string. Reverting to the default behaviour fixes this, and I can find no negative side effects in my tests.

### CODE REVIEW

**Comment by jdarwood007** [comment]
#1794 was the PR that added that code.  Any issues you foresee from what that PR was trying to fix?

**Comment by Sesquipedalian** [comment]
No. There was no description in that PR and I could not find a related issue, so I had to try to figure out what the purpose of the code changes was myself. As far as I can tell, the other changes in that PR did improve some stuff, whereas the custom 'matches' callback doesn't appear to have accomplished anything except introducing this bug. Perhaps the custom code originally provided a workaround for a bug in At.js that was later solved upstream, but either way it doesn't do anything useful now. 🤷🏻‍♂️

For what its worth, I initially tried seeing if I could fix the custom code, and was making progress until I realized that my fixes were essentially just reimplementing what was in the default code anyway.

File: Themes/default/scripts/mentions.js [hunk 1]
```diff
@@ -6,25 +6,6 @@ var atwhoConfig = {
 	show_the_at: true,
```
Comment (live627) [inline Themes/default/scripts/mentions.js:6]:
```suggestion
	show_the_at: true,
	startWithSpace: true,
```

**Review by live627 — CHANGES_REQUESTED** [review]
I have found that the custom matcher required whitespace before the keyword to mat ch. This restores that behavior.

**Comment by Sesquipedalian** [comment]
Nice. Suggestion committed.

**Review by live627 — APPROVED** [review]

**Comment by jdarwood007** [comment]
Thanks for the answer, I wasn't sure what the original code was intending to do either, so I was seeing if somebody else understood.

**Comment by live627** [comment]
I only figured it out because of the change in behavior after I applied the patch.
