### PR TITLE
Remove trailing colon from event time

### LINKED ISSUE #6791: default_time_format not honoring seconds
#### Description
I see "Invalid Date" errors entering events into the calendar on my migrated test 2.1 forum.  

Then I noticed the times looked funky:
invalid-date-migrated-forum

It appears the :%S to include seconds in the time is not working.  This is the default time format:
image

Note the DB allows seconds, so I think the :%S should be valid:
image

### Steps to reproduce
1. Add :%S to the default time format
2. Add an event in the calendar

OR....

1. Add an event in the calendar on a migrated forum that had :%S specified (the old default)

### Environment (complete as necessary)
- Version/Git revision: Current
- Database Type: mysql
- Database Version: 5.7
- PHP Version: 7.4

### Additional information/references
This is the **_2.0 default time format_** upon install - unless overridden, it specifies seconds:
image

This is the **_2.1 default time format_** upon install:
image

Not a big priority - workaround is easy, to remove the :%S.

### PR DESCRIPTION
**Pull request by BrickOzp**
When creating a new event, the time box had a trailing colon, like
9:10: or 9:10: am. Removed that.

Signed-off-by: Oscar Rydhé oscar.rydhe@gmail.com

### CODE REVIEW

**Review by Sesquipedalian — APPROVED** [review]

**Comment by sbulen** [comment]
What is very interesting is the row that maps %S to a space...   Do we get seconds if that is removed?

If the string specifies seconds, I think we should honor it instead of stripping it.

**Comment by BrickOzp** [comment]
Made a quick test. Even if I show the seconds they will not get saved. Have not investigated why

**Comment by BrickOzp** [comment]
Turns out seconds are stored in the db, but must get trimmed away on display.
Think we must decide what to do here. Always show seconds (if part of time format) or never show seconds (like now)

**Comment by sbulen** [comment]
Testing this PR and I am still seeing the : when am/pm is specified:
image

This is what we're getting internally, so the trim doesn't work as-is - not on its own anyway:
image

**Comment by sbulen** [comment]
My suggestion is to put back your original mapping of ':%S' to '', plus also keep the trim (a good safety measure since there is a lot of mapping items to '').

File: Sources/Calendar.php [hunk 1]
```diff
@@ -293,6 +293,8 @@ function CalendarPost()
 		'%T' => '%l:%M',
 	));
 
+	$time_string = trim($time_string, ':');
```
Comment (Sesquipedalian) [inline Sources/Calendar.php]:
```suggestion
	$time_string = preg_replace('~:(?=\D|$)~', '', $time_string);
```

This will remove any colon that is followed by a non-digit or the end of the string.

| Before | After |
|--------|-------|
| '9:45:00 am' | '9:45:00 am' |
| '9:45: am' | '9:45 am' |
| '9:45:am' | '9:45am' |
| '9:: am' | '9 am' |
| '9::am' | '9am' |
| '9:45:' | '9:45' |

File: Sources/Post.php [hunk 2]
```diff
@@ -296,6 +296,8 @@ function Post($post_errors = array())
 			'%T' => '%l:%M',
 		));
 
+		$time_string = trim($time_string, ':');
```
Comment (Sesquipedalian) [inline Sources/Post.php]:
```suggestion
		$time_string = preg_replace('~:(?=\D|$)~', '', $time_string);
```

File: Sources/Subs-Calendar.php [hunk 3]
```diff
@@ -1737,6 +1737,8 @@ function buildEventDatetimes($row)
 			'%T' => '%l:%M',
 		));
 
+	$time_format = trim($time_format, ':');
```
Comment (Sesquipedalian) [inline Sources/Subs-Calendar.php]:
```suggestion
	$time_format = preg_replace('~:(?=\D|$)~', '', $time_format);
```

**Review by Sesquipedalian — CHANGES_REQUESTED** [review]
This `preg_replace()` should remove stray colons even in the middle of strings.

**Comment by sbulen** [comment]
That'll work, too!

File: Sources/Calendar.php (hunk 1 above)
Comment (BrickOzp) [reply Sources/Calendar.php]: The time_string contains the time format, so no digits. But I think I managed to modify it to work.

File: Sources/Calendar.php [hunk 4]
```diff
@@ -293,6 +293,8 @@ function CalendarPost()
 		'%T' => '%l:%M',
 	));
 
+	$time_string = preg_replace('~:(?=\s|$)~', '', $time_string);
```
Comment (Sesquipedalian) [inline Sources/Calendar.php]: Only checking for a space or end of string could still produce `9:45:am`, `9:45:AM`, `9:45:EST`  or `9:45:-5000` in the output if the original time format contained something like `:%S%p`, `:%S%P`, `:%S%z`, or `:%S%Z` (no space after `%S`)

The following should fix that.
```suggestion
	$time_string = preg_replace('~:(?=\s|$|%[pPzZ])~', '', $time_string);
```

File: Sources/Post.php [hunk 5]
```diff
@@ -296,6 +296,8 @@ function Post($post_errors = array())
 			'%T' => '%l:%M',
 		));
 
+		$time_string = preg_replace('~:(?=\s|$)~', '', $time_string);
```
Comment (Sesquipedalian) [inline Sources/Post.php]:
```suggestion
		$time_string = preg_replace('~:(?=\s|$|%[pPzZ])~', '', $time_string);
```

File: Sources/Subs-Calendar.php [hunk 6]
```diff
@@ -1737,6 +1737,8 @@ function buildEventDatetimes($row)
 			'%T' => '%l:%M',
 		));
 
+	$time_format = preg_replace('~:(?=\s|$)~', '', $time_format);
```
Comment (Sesquipedalian) [inline Sources/Subs-Calendar.php]:
```suggestion
	$time_format = preg_replace('~:(?=\s|$|%[pPzZ])~', '', $time_format);
```

**Review by Sesquipedalian — CHANGES_REQUESTED** [review]

File: Sources/Calendar.php (hunk 1 above)
Comment (Sesquipedalian) [reply Sources/Calendar.php]: Derp. You are right. See comments below.

File: Sources/Calendar.php (hunk 4 above)
Comment (BrickOzp) [reply Sources/Calendar.php]: Thanks

**Review by live627 — APPROVED** [review]
