### PR TITLE
[2.1] Fix quotes in names for mention handling

### LINKED ISSUE #8820: [2.1 & 3.0]: Mentions don't work for names with apostrophes
### Basic Information

Image

### Steps to reproduce

1. Edit any name - add apostrophe
2. Try to mention that member

### Expected result

_No response_

### Actual result

_No response_

### Version/Git revision

70c0b0a80224d2bec667e8a7278bc8233372d4d8

### Database Engine

All

### Database Version

11.7.2-MariaDB

### PHP Version

8.3.22

### Logs

```shell

```

### Additional Information

I noticed that when a user edits their display name in the profile and adds an apostrophe, the value is saved differently:
- 2.1: `Test&#39;Name`
- 3.0: `Test'Name`

### PR DESCRIPTION
**Pull request by jdarwood007**
Fixes #8820

### CODE REVIEW

File: Themes/default/scripts/mentions.js [hunk 1]
```diff
@@ -43,6 +43,27 @@ var atwhoConfig = {
 					callback(callbackArray);
 				}
 			});
+		},
+		tplEval: function (tpl, map, caller) {
+			console.log(tpl,map,caller);
```
Comment (dragomano) [inline Themes/default/scripts/mentions.js]: `console.log`

**Review by dragomano — APPROVED** [review]

**Review by Sesquipedalian — APPROVED** [review]
