### PR TITLE
Likes perm

### LINKED ISSUE #1678: download packages page broken
looks like the section under download new packages is not showing

### PR DESCRIPTION
**Pull request by MissAllSunday**
- Adds json response support to Likes class
- Add a collapsed icon on Download new packages sectio fixes #1678
- Adds and implements likes permissions and a master setting.
- Removes karma feature.

Don't really like how the like permissions were named, specially the likes_like.
Didn't add a real description for the likes admin setting, not good at it.

### CODE REVIEW

**Comment by XinYenFon** [comment]
We are going to offer Karma as a modification, we need to put a checkbox to confirm they want to remove karma table, otherwise that could be really wrong. All their data will be wiped.

**Comment by Dragooon** [comment]
Did a quick read and most of it looks fine, but I agree with @Antes, we shouldn't remove existing Karma data in case someone wants to keep that.

Also the mentions placeholders are for me, correct?

**Comment by Dragooon** [comment]
Eh...I guess my recent changes are causing merge conflicts with this PR

File: Sources/PackageGet.php [hunk 1]
```diff
@@ -174,7 +174,24 @@ function PackageServers()
...
-		$(\'.new_package_content\').css(\'display\') == \'none\' ? $(\'.new_package_content\').show(\'slow\') : $(\'.new_package_content\').hide(\'slow\'); 
+		var collapseState = $(\'.new_package_content\').css(\'display\');
+		var icon = $(\'.download_new_package\').children(\'span\');
+		var collapsedDiv = $(\'.new_package_content\');
+
+		if (collapseState == \'none\')
+		{
+			collapsedDiv.show(\'slow\');
+			icon.removeClass(\'toggle_down\').addClass(\'toggle_up\');
+			icon.prop(\'title\', '. JavaScriptEscape($txt['hide']) .');
```
Comment (live627) [inline Sources/PackageGet.php:185]: This feels weird. Shouldn't it use attr() instead?

Comment (Dragooon) [inline Sources/PackageGet.php:185]: .prop() and .attr() essentially do the same thing but .prop() is generally the recommended way of doing things since it deals with Javascript properties instead of HTML attributes (checkout the jQuery docs for .prop() to know more)

**Comment by MissAllSunday** [comment]
Moved the karma deleting stuff to upgrade.php, added a checkbox and fixed the merge conflict.

**Comment by Dragooon** [comment]
So...this is good for merge?

**Comment by MissAllSunday** [comment]
yep

**Comment by MissAllSunday** [comment]
oops, just found out I made a huge boo boo 

The queries for removing the karma settings are all borked, I didn't get the actual error because for some reason php_version_check() is actually returning false on my php version: 5.3.13

I'll create another PR
