### PR TITLE
Change the default session serialize_handler to php_serialize Fixes #4444

### LINKED ISSUE #4444: Session 'failed to decode' messages
Not all fields in the session are properly encoded.  This results in occasional 'failed to decode' messages.  

I believe the bug is this:  the $_SESSION['last_ss'] is populated with the contents of the last search.  When UTF8 characters are searched for, they are not properly encoded here.   The session encoding & decoding has a problem with this.  

To reproduce:  Search for any special UTF8 characters...   Try this: 'Река неслася; бедный чёлн'

This occurs in 2.1 & in 2.0 at the moment.  This even occurs if your DB is properly setup as UTF8.  

Note that everything works perfectly.  Your search works!  But this message is logged in the background & your session is destroyed & rebuilt.

### PR DESCRIPTION
**Pull request by albertlast**
by keeping run able on php 5.4
the full story you find in the issue: #4444 and related sm.org topic

i "copy" the logic from wikimedia: https://github.com/wikimedia/php-session-serializer/blob/master/src/Wikimedia/PhpSessionSerializer.php#L70

### CODE REVIEW

File: Sources/Session.php [hunk 1]
```diff
@@ -62,7 +62,9 @@ function loadSession()
 		// Use database sessions? (they don't work in 4.1.x!)
 		if (!empty($modSettings['databaseSession_enable']))
 		{
-			@ini_set('session.serialize_handler', 'php');
+			@ini_set('session.serialize_handler', 'php_serialize');
+			if(ini_get( 'session.serialize_handler') != 'php_serialize')
```
Comment (colinschoen) [inline Sources/Session.php]: Nit: `if(ini_get( 'session.serialize_handler')` -> `if (ini_get('session.serialize_handler')`

**Review by colinschoen — CHANGES_REQUESTED** [review]

File: Sources/Session.php [hunk 2]
```diff
@@ -62,7 +62,9 @@ function loadSession()
 		// Use database sessions? (they don't work in 4.1.x!)
 		if (!empty($modSettings['databaseSession_enable']))
 		{
-			@ini_set('session.serialize_handler', 'php');
+			@ini_set('session.serialize_handler', 'php_serialize');
+			if(ini_get('session.serialize_handler') != 'php_serialize')
```
Comment (colinschoen) [inline Sources/Session.php]: Still missing space after `if`

**Review by colinschoen — APPROVED** [review]
LGTM approval
