### PR TITLE
Doesn't assume $user_info is populated in getUserTimezone()

### LINKED ISSUE #7184: Undefined index errors in getUserTimezone() when spiders crawl forum
#### Description
When a search engine crawls the forum, `getUserTimezone()` is called before `$user_info['is_guest']` and `$context['user']` have been set, which causes errors because `getUserTimezone()` assumes that they already have been set.

### Steps to reproduce
1. Set the "Search Engine Tracking level" setting to anything other than "Disabled"
2. Set your browser's User Agent string to "Googlebot/2.1"
3. Browse the forum.

### Environment (complete as necessary)
- Version/Git revision: e52c55f
- Database Type: N/A
- Database Version: N/A
- PHP Version: N/A

### Additional information/references
Backtrace:
```
#0: smf_error_handler()
Called from /Users/jon/Sites/dev/Sources/Subs.php on line 6842
#1: getUserTimezone()
Called from /Users/jon/Sites/dev/Sources/Subs.php on line 926
#2: smf_strftime()
Called from /Users/jon/Sites/dev/Sources/ManageSearchEngines.php on line 561
#3: logSpider()
Called from /Users/jon/Sites/dev/Sources/ManageSearchEngines.php on line 541
#4: SpiderCheck()
Called from /Users/jon/Sites/dev/Sources/Load.php on line 803
#5: loadUserSettings()
Called from /Users/jon/Sites/dev/index.php on line 217
#6: smf_main()
Called from /Users/jon/Sites/dev/index.php on line 187
```
It looks like I introduced this in #7179. I will submit a fix shortly.

### PR DESCRIPTION
**Pull request by Sesquipedalian**
Fixes #7184

### CODE REVIEW

File: Sources/Subs.php [hunk 1]
```diff
@@ -6855,19 +6855,16 @@ function getUserTimezone($id_member = null)
...
+	$request = $smcFunc['db_query']('', '
+		SELECT timezone
+		FROM {db_prefix}members
+		WHERE id_member = {int:id_member}',
+		array(
+			'id_member' => $id_member,
+		)
+	);
+	list($timezone) = $smcFunc['db_fetch_row']($request);
+	$smcFunc['db_free_result']($request);
```
Comment (jdarwood007) [inline Sources/Subs.php:6867]: You should put back the if logic but use !empty.  We can't query the database for id_member = 0.
Unless I missed something.

Comment (Sesquipedalian) [reply Sources/Subs.php:6867]: You are correct. Running the query doesn't break anything, but it is pointless. I have restored it in #7189.
