### PR TITLE
Upgrade fixes

### LINKED ISSUE #2557: upgrade does not finish
+++  Add an order value to each existing cust profile field. done.
 +++  Converting member values...Unknown column 'msn' in 'field list'

2.1 upgrade to 2.1.

### PR DESCRIPTION
**Pull request by Oldiesmann**
1. Rework converting profile fields to prevent errors (fixes #2557)
2. Include DbExtra so $smcFunc['db_create_table'] will work
3. Reword the "You don't have ALTER privileges..." message slightly
4. Include new privilege checks for cmd as well.

Signed-off-by: Michael Eshom oldiesmann@oldiesmann.us

### CODE REVIEW

File: other/upgrade_2-1_postgresql.sql [hunk 1]
```diff
@@ -907,12 +907,17 @@ INSERT INTO {$db_prefix}custom_fields (col_name, field_name, field_desc, field_t
...
+$possible_columns = array('aim', 'icq', 'msn', 'yim', 'location', 'gender');
+
+// Find values that are in both arrays
+$select_columns = array_intersect($possible_columns, $results);
+
+if (!empty($select_columns))
 {
 	$request = $smcFunc['db_query']('', '
-		SELECT id_member, aim, icq, msn, yim, location, gender
+		SELECT ', implode(',', $select_columns), '
```
Comment (Dragooon) [inline other/upgrade_2-1_postgresql.sql]: Same as above, id_member too here

File: other/upgrade_2-1_mysql.sql [hunk 2]
```diff
@@ -850,12 +850,17 @@ INSERT INTO `{$db_prefix}custom_fields` (`col_name`, `field_name`, `field_desc`,
...
+$possible_columns = array('aim', 'icq', 'msn', 'yim', 'location', 'gender');
+
+// Find values that are in both arrays
+$select_columns = array_intersect($possible_columns, $results);
+
+if (!empty($select_columns))
 {
 	$request = $smcFunc['db_query']('', '
-		SELECT id_member, aim, icq, msn, yim, location, gender
+		SELECT ', implode(',', $select_columns) ,'
```
Comment (Dragooon) [inline other/upgrade_2-1_mysql.sql]: You'd also need to select id_member
