### PR TITLE
Do not attempt to convert backup tables to UTF-8

### LINKED ISSUE #7823: Upgrade converting UTF-8 may sometimes convert backup tables
#### Description
I noticed this while doing a test upgrade on a forum
Screen Shot 2023-08-09 at 12 41 03 PM

The issue is because the forum has no prefix.

### Steps to reproduce
1. Use no prefix on `$db_prefix = '';`
2.  Perform a upgrade, instructing to create backup tables
3. During the UTF-8 conversion, backup tables are converted.

### Environment (complete as necessary)
- Version/Git revision: 2.1.4
- Database Type: MySQL
- Database Version: 8.0
- PHP Version: 8.1

### Additional information/references
I don't know if we can come up with a fix at the moment.  This is a really unique edge case.  I'm documenting it at least so we know this occurs.

### PR DESCRIPTION
**Pull request by jdarwood007**
Fixes #7823

### CODE REVIEW

File: other/upgrade.php [hunk 1]
```diff
@@ -3252,6 +3252,10 @@ function ConvertUtf8()
 		db_extend();
 		$queryTables = $smcFunc['db_list_tables'](false, $db_prefix . '%');
 
+		$queryTables = array_values(array_filter($queryTables, function($v){
+			return !(stripos($v, 'backup_') === 0);
```
Comment (live627) [inline other/upgrade.php]:
```suggestion
			return stripos($v, 'backup_') !== 0;
```

just a silly change

Comment (jdarwood007) [reply other/upgrade.php]: Well that could mean it would match `my_backup_table`.  Instead of just matching `backup_table`.  That was my intention at least.

Comment (Sesquipedalian) [reply other/upgrade.php]: No, they are equivalent statements.

Comment (jdarwood007) [reply other/upgrade.php]: oh yea, its still strict type checking.

**Review by live627 — APPROVED** [review]
