### PR TITLE
Fix bug where membergroups are not displayed via SSI Who's Online

### LINKED ISSUE #6417: Membergroups are not displayed via SSI Who's Online
### Steps to reproduce
1. Enable "Show group key on board index" option (Admin > Configuration > Current Theme)
2.  Open http://yoursite/ssi_examples.php, select Members > Who's Online section. You won't see any membergroups.

### Additional information/references
This problem is actual for SMF 2.0 too.

### PR DESCRIPTION
**Pull request by dragomano**
Fixes #6417 

Signed-off-by: Bugo <bugo@dragomano.ru>

### CODE REVIEW

File: SSI.php [hunk 1]
```diff
@@ -1289,9 +1289,20 @@ function ssi_whosOnline($output_method = 'echo')
 			', implode(', ', $return['list_users_online']);
 
 	// Showing membergroups?
-	if (!empty($settings['show_group_key']) && !empty($return['membergroups']))
+	if (!empty($settings['show_group_key']) && !empty($return['online_groups']))
+	{
+		$membergroups = cache_quick_get('membergroup_list', 'Subs-Membergroups.php', 'cache_getMembergroupList', array());
+
+		$groups = array();
+		foreach ($return['online_groups'] as $group)
```
Comment (live627) [inline SSI.php:1297]: holup.... couldn't this use `isset()`?

**Review by MissAllSunday — APPROVED** [review]
