### PR TITLE
This has proven difficult to get right

### LINKED ISSUE #6267: No new entries in Moderation Log after upgrade to RC3
#### Description
After upgrading my forums to RC3 (from SMF 2.1RC2+, commit fc9fc21), no new entries in the Moderation Log. All the old entries persist in the log.

### Steps to reproduce
1.  Upgrade forum to latest Github version cb165c7
2.  Perform some moderation action (delete a post ot topic, move a topic, sticky a topic etc.)

### Environment (complete as necessary)
- Version/Git revision: cb165c7
- Database Type: MariaDB
- Database Version: 10.3.24
- PHP Version: 7.4.9

### Additional information/references

### PR DESCRIPTION
**Pull request by live627**
Fix #6267

### CODE REVIEW

File: Sources/Logging.php [hunk 1]
```diff
@@ -442,7 +442,7 @@ function logActions($logs)
 
 	foreach ($logs as $log)
 	{
-		if ((empty($modSettings[$log['log_type'] . 'log_enabled']) || !isset($log_types[$log['log_type']])) && !in_array($log['action'], $always_log))
+		if (!in_array($log['action'], $always_log) && (empty($modSettings[$log['log_type'] . 'log_enabled']) || !isset($log_types[$log['log_type']])))
```
Comment (dragomano) [inline Sources/Logging.php]: `in_array($log['action'], $always_log)` instead of `!in_array($log['action'], $always_log)` to get moderation log work properly.

Comment (Hatshepsut71) [reply Sources/Logging.php]: Yes, with this correction Moderation Log now is working properly.

**Review by MissAllSunday — APPROVED** [review]
